#!/usr/bin/env bash
#
# Configure/Switch my audio devices.

# case $1 in
# 	(PCH)
# 		c=PCH;
# 		d=0;;
# 	(HDMI)
# 		c=HDMI;
# 		d=3;;
# 	(*)
# 		printf '?\n';
# 		exit 1;;
# esac;

# ed -s "$HOME/".asoundrc <<S
# /^c = /s/=.*$/= $c/
# /^d = /s/=.*$/= $d/
# w
# S

case ${PRODUCT_NAME_SUM:=$(get-product-name-by-md5sum)} in
	(dd791b3dd44b647e91524123fa1c6d0f)
		case ${1,,} in
			(pch|hdmi)
				exec ln -fsr "$HOME/.asoundrc_${1,,}" "$HOME/.asoundrc";;
		esac;
esac;

! :;

# vim: set ft=sh :
