#!/usr/bin/env bash
#
# Prepare the full backup of my system.

cd -- "$HOME";

printf -v horiz %\*s 80 '';
function PrintHeader {
    printf %s\\n ${horiz// /-} $1 1>&2;
};

# PrintHeader update-packages;
# update-packages;

PrintHeader backup-meta-apt;
backup-meta-apt;

PrintHeader backup-meta-bin;
backup-meta-bin;

PrintHeader backup-meta-init;
backup-meta-init;

PrintHeader cclean;
cclean;

PrintHeader etckeeper;
cd / ||
    exit 1;
printf -v d %\(%s\)T -1;
sudo etckeeper commit $d\ prepare\ backup;

# vim: set ts=4 sw=4 tw=0 et :
