#!/bin/sh
#
# Backup infos about installed packages on Debian.

backup_dir=${XDG_BACKUP_HOME:?};

sudo rm -rv -- "$backup_dir/"pkgs;
mkdir -pv -- "$backup_dir/"pkgs;

cd -- "$backup_dir/"pkgs ||
    exit 1;

COLUMNS=200 dpkg-query -l > ./query.txt;
sudo sh -c '
    apt-cache policy > ./cache.txt;
    apt-mark showauto > ./auto.txt;
    apt-mark showmanual > ./manual.txt;
    # cp -v /etc/apt/trusted.gpg ./trusted.gpg;
    apt-clone clone .;
';

# dpkg --get-selections |
# mawk '!/deinstall|purge|hold/ { print $1 }' > ./packages.txt;

# sudo find /etc/apt/sources.list* \
#     -type f \
#     -name '*.list' \
#     -exec sh -c '
#         printf "%s\n## " "$1";
#         grep "^[[:space:]]*[^#[:space:]]" "$1";' \
#     _ {} \; > ./sources.list;

# vim: set ft=sh :
