#!/usr/bin/env bash
#
# Prepare the full backup of my system.

cd -- "$HOME";

printf -v horiz '%*s' "80" '';
function PrintHeader {
    printf '%s\n' "${horiz// /-}" "$1" 1>&2;
};

update-packages;

'PrintHeader' "Programs";
backup-meta-bin;

'PrintHeader' "Inits";
backup-meta-init;

'PrintHeader' "etckeeper";
(
    cd -- / || exit 1;
    printf -v d '%(%s)T' -1;
    sudo etckeeper commit "${d}: prepare backup";
);

'PrintHeader' "newsbeuter";
rm -fv "${HOME}/.newsbeuter/newsbeuter_cache.db";

'PrintHeader' "ccleaner";
cclean;

# vim: set ts=4 sw=4 tw=0 et :
