#!/bin/sh
#
# Backup inits.

{
    find /etc/init.d/ -perm /111 -type f -printf %f\\n;
    find /etc/init -type f -printf %f\\n;
} |
sort -u > "${XDG_VAR_HOME:?}/"backups/init.txt;

# vim: set ts=4 sw=4 tw=0 et :
