#!/bin/sh
#
# Remove duplicates from bash history and rewrite file.

sed -e 's:^[[:space:][:cntrl:]]*::; s:[[:space:][:cntrl:]]*$::' "${HISTFILE:?}" |
nl |
sort -u -k 2 |
sort -n |
cut -f 2 > "$HISTFILE.$$";

exec mv -- "$HISTFILE.$$" "$HISTFILE";

# vim: set ft=sh :
