#!/bin/sh
#
# Remove duplicates from bash history and rewrite file.

exec sed -e 's:^[[:space:][:cntrl:]]*::; s:[[:space:][:cntrl:]]*$::' -- "${HISTFILE:?}" |
    exec nl |
    exec sort -u -k 2 |
    exec sort -n |
    command -- cut -f 2 >"$HISTFILE.$$"

test -s "$HISTFILE.$$" &&
    exec mv -- "$HISTFILE.$$" "$HISTFILE"

# vim: set ft=sh :
