#!/usr/bin/env dash
#
# Remove duplicates in .bash_history.
# http://unix.stackexchange.com/questions/48713/how-can-i-remove-duplicates-in-my-bash-history-preserving-order

nl "$HISTFILE" \
| sed 's/[[:space:]]*$//' \
| sort -k 2 -k 1,1nr \
| uniq -f 1 \
| sort -n \
| cut -f 2 \
> "${HISTFILE}~";

mv -- "${HISTFILE}~" "$HISTFILE"

# vim: set ts=8 sw=8 tw=0 et :
