#!/bin/sh
#
# Spotify: Take pub list1 and create a list with unplayable tracks.
# See: https://developer.spotify.com/documentation/general/guides/track-relinking-guide/

list1=${1:?};
list2=${2:?};
token=${3:?};
market=${4:-DE};

list=/tmp/$list1.json;

bspot getTracksInMarket "$list1" "$token" "$market" > "$list";

bspot clearList "$list2" "$token";

jq -e -r \
	'.items[] | if .track.is_playable then empty else .track.uri end' "$list" |
bspot addTracks "$list2" "$token";

# vim: set ft=sh :
