#!/bin/sh
#
# Spotify: Get track infos of a public playlist.

list=${1:?};
token=${2:?};

bspot getTracksObjects "$list" "$token" > "/tmp/$list.json";

jq -e -c '
	.items[] |
	[
		([.track.artists[].name] | join(" / ") ),
		.track.name, .track.track_number,
		.track.disc_number,
		.track.album.name,
		.track.duration_ms,
		.track.uri,
		.added_at
	]
' "/tmp/$list.json" |
LC_ALL=en_US.UTF-8 sort;

# vim: set ft=sh :
