#!/usr/bin/env bash
#
# Spotify: Take pub list1 and create audio-featured public lists.

user=${1:?};
token=${2:?};
file=${3:-$XDG_VAR_HOME/lib/bspot_create_featured_list.sh};

. "$file" ||
	exit 1;

_list1=/tmp/$list1.json;

bspot getTracks "$user" "$list1" "$token" |
	cut -d : -f 3 |
	bspot getTracksFeatures "$token" > "$_list1";

for f in "${!Features[@]}";
do
	bspot clearList "$user" "${Features[$f]}" "$token";
	jq -r ".audio_features[] | [.$f, .uri] | @tsv" "$_list1" |
		LC_ALL=C sort -k 1gr,1gr -k 2d,2d |
		cut -f 2 |
		bspot addTracks "$user" "${Features[$f]}" "$token";
done;

# vim: set ft=sh :
