#!/bin/sh
#
# Take pub list1, shuffle it and add the songs to cleared pub list2.

list1=${1:?}
list2=${2:?}
token=${3:?}

command -- bspot clearList "$list2" "$token"

exec bspot getTracks "$list1" "$token" |
    exec shuf |
    command -- bspot addTracks "$list2" "$token"

# vim: set ft=sh :
