#!/usr/bin/env bash
#
# Spotify: Take pub list1 and sort it by label.

user=${1:?};
list1=${2:?};
list2=${3:?};
token=${4:?};

bspot clearList "$user" "$list2" "$token";

bspot getAlbums "$user" "$list1" "$token" > /tmp/bspot_albums.txt;

paste /tmp/bspot_albums.txt <(
    cut -f 1 /tmp/bspot_albums.txt |
    cut -d : -f 3 |
    bspot getAlbumsObjects "$token" |
    jq -e -r '.albums[].label | [.] | @sh';
) |
LC_ALL=C sort -k 3df,3df -k 1d,1d -k 2d,2d |
cut -f 2 |
bspot addTracks "$user" "$list2" "$token";

# vim: set ts=4 sw=4 tw=0 et :
