#!/usr/bin/env bash
#
# Take pub list1 and create audio-featured public lists.

token=${1:?}
file=${2:-${XDG_VAR_HOME:?}/lib/bspot/bspot_create_featured_list.sh}

. "$file" ||
    exit 1

_list1=/tmp/$list1.json

exec -- bspot getTracks "$list1" "$token" |
    exec -- cut -d : -f 3 |
    command -- bspot getTracksFeatures "$token" >"$_list1"

for f in "${!Features[@]}"; do
    command -- bspot clearList "${Features[$f]}" "$token"
    exec -- jq -r ".audio_features[] | [.$f, .uri] | @tsv" "$_list1" |
        LC_ALL=C exec -- sort -k 1gr,1gr -k 2d,2d |
        exec -- cut -f 2 |
        command -- bspot addTracks "${Features[$f]}" "$token"
done

# vim: set ft=zsh :
