#!/bin/sh
#
# bspwm: external_rules_command

id=${1?} \
  instance=$3 \
  class=$2;

case $class in
(Emacs) echo state=tiled\ layer=normal;;
(Firefox|Firefox-esr|Iceweasel) echo desktop=^2;;
(Gimp*) echo follow=on;;
(Gitk) echo state=floating\ layer=normal;;
(MPlayer) echo state=floating\ layer=normal;;
(Pidgin) echo desktop=^3;;
(Pinentry-gtk-2) echo state=floating\ layer=above;;
(Spotify) echo desktop=^5;;
(XCalc) echo state=floating\ layer=normal;;
(Xmessage) echo state=floating\ layer=normal;;
(Xombrero) echo desktop=^2;;
([cC]hromium|Chromium-browser) echo desktop=^2;;
(mpv) echo state=floating\ layer=normal;;
(stj[12]) echo state=floating\ layer=above\ border=on\ sticky=on;;
(weechat) echo desktop=^3;;
('')
    case $(ps -p "$(xdo pid $id)" -o comm= 2>/dev/null) in
    (spotify)
        echo desktop=^5;;
    esac;;
esac;

# vim: set ts=4 sw=4 tw=0 et :
