#!/bin/sh
#
# Configure camera.

: "${XDG_CONFIG_HOME:?}" "${PRODUCT_NAME_SUM:=$(get-product-name-by-md5sum)}";

test-xorg ||
	exit 1;

test -r "$XDG_CONFIG_HOME/computer/$PRODUCT_NAME_SUM/camera" &&
	xinput --disable "$(cat "$XDG_CONFIG_HOME/computer/$PRODUCT_NAME_SUM/camera")";

# vim: set ft=sh :
