#!/bin/sh
#
# Clean up some dirs and files.

rm -frv -- \
    "$HOME/".adobe \
    "$HOME/".cache \
    "$HOME/".gconf \
    "$HOME/".git-credential-cache \
    "$HOME/".gnome2 \
    "$HOME/".gnome2_private \
    "$HOME/".icedteaplugin \
    "$HOME/".macromedia \
    "$HOME/".thumbnails \
    "$HOME/"cache/* \
    "$XDG_CONFIG_HOME/"freshwrapper-data \
    "$XDG_DATA_HOME/"webkit \
    "${XDG_CACHE_HOME:?}/"* \
    "${XDG_CONFIG_HOME:?}/"cef_user_data \
    "${XDG_DATA_HOME:?}/"gegl-0.3;

rm -fv -- \
    "$HOME/".gksu.lock \
    "$HOME/".newsbeuter/newsbeuter_cache.db \
    "$HOME/".recentf \
    "$HOME/".recently-used \
    "$XDG_DATA_HOME/"recently-used.xbel;

# vim: set ts=4 sw=4 tw=0 et :
