#!/bin/sh
#
# Turn all downloaded wir bare git repositories into normal repos.

src=${1:-$HOME/src/wir}

exec find -H "$src" \
    -mindepth 2 \
    -maxdepth 2 \
    -type d \
    -print0 |
    command -- xargs -0 -n 1 -P 0 -- sh -c '
        test -d "$1/.git" ||
            exit 1

        export \
            GIT_DIR \
            GIT_WORK_TREE;
        GIT_WORK_TREE=$1
        GIT_DIR=$1/.git

        eval "$(exec git config --local --get --bool core.bare)" ||
            exit 0

        command -- git config --local core.bare false
        command -- git config --local remote.origin.mirror false
        command -- git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"

        command -- git fetch origin

        head=$(exec git symbolic-ref --short HEAD)

        command -- git branch --set-upstream-to="origin/$head" "$head"

        command -- git checkout "$head"

        command -- git submodule sync --recursive
        exec git submodule update --init --recursive --jobs 12
    ' --

# vim: set ft=sh :
