#!/usr/bin/env bash
#
# Browse the history of chromium via fzf, and then open selection.
# https://github.com/junegunn/fzf/wiki/Examples#browsing-history

cols=$(( $(tput cols) / 3 ))
sep='{{::}}'

cp -f "${XDG_CONFIG_HOME}/chromium/Default/History" /tmp/h.chromium

while
        read -r
do
        setsidw chromium "$REPLY" 1>/dev/null 2>&1
done < <(
        sqlite3 -separator "$sep" /tmp/h.chromium \
                "select substr(title, 1, ${cols}), url
                from urls
                order by last_visit_time desc" \
        | awk -F "$sep" '{printf "%-'$cols's  \x1b[36m%s\n", $1, $2}' \
        | fzf --ansi --multi \
        | sed 's#.*\(https*://\)#\1#';
)

# vim: set ts=8 sw=8 tw=0 et :
