#!/bin/sh
#
# Wrapper: chromium

export CHROME_WRAPPER=$0;

exec /usr/bin/chromium \
    --enable-remote-extensions \
    --disable-infobars \
    --disable-sync-preferences \
    --disable-translate \
    ${1:+"$@"};

# vim: set ts=4 sw=4 tw=0 et :
