#!/bin/sh
#
# Wrapper: chromium

. /etc/chromium.d/apikeys;
. /etc/chromium.d/default-flags;
. /etc/chromium.d/pepperflashplugin-nonfree;

exec /usr/lib/chromium/chromium $CHROMIUM_FLAGS \
    --disable-infobars \
    --disable-sync-preferences \
    --disable-translate \
    --no-first-run \
    ${1:+"$@"};

# vim: set ts=4 sw=4 tw=0 et :
