#!/usr/bin/env bash
#
# Simple X primary selection manager.
#
# Depends on: autocutsel -fork -selection PRIMARY -buttonup
# Idea from: http://chneukirchen.org/dotfiles/bin/backclip

function Clipbuffer::Daemon {
    typeset -i i=-1;

    mkdir -p -m 700 -- "$xsels";
    printf %d $$ > "$xsels/"$$.pid;

    xprop -root -spy CUT_BUFFER0 |
    while
        read;
    do
        oi=$i;
        xorg-selection-primary-out > "$xsels/".$oi;
        cmp -s "$xsels/".$oi "$xsels/"$oi ||
            mv -- "$xsels/".$oi "$xsels/"$((i = ++i % 32));
    done;
};

function Clipbuffer::Kill {
    typeset p;
    shopt -s nullglob;

    for p in "$xsels/"?*.pid; do
        p=${p##*/};
        pkill -TERM -P "${p%.pid}";
    done;

    if
        $opt_clear;
    then
        rm -fr -- "$xsels" 2>/dev/null;
    else
        rm -f -- "$xsels/"?*.pid 2>/dev/null;
    fi;

    xsel -l /dev/null --clear --clipboard;
    xsel -l /dev/null --clear --primary;
};

function Clipbuffer::Clip {
    typeset clip menu;

    if
        test-tty 2>/dev/null;
    then
        menu=fzf;
    else
        menu=dmenu2;
    fi;

    shopt -s nullglob;
    shopt -s extglob;

    printf -v clip %s "$(
        # printf '%s\n' "$xsels/"+([0-9]) |
        # sort -n |
        # xargs -I f sh -c "tr '[:space:]' ' ' < 'f'; echo" |
        # nl -w1 -s ' ' |
        # tac |

        for f in "$xsels/"+([0-9]); do
            printf '%d ' "${f##*/}";
            tr '[:space:]' ' ' < "$f";
            printf '\n';
        done |
        sort -nr |
        menu "$menu";
    )";

    [[ -n $clip ]] &&
        if
            $opt_board;
        then
            xsel -l /dev/null --clear --clipboard;
            xorg-selection-clipboard-in < "$xsels/${clip%% *}";
        else
            xsel -l /dev/null --clear --primary;
            xorg-selection-primary-in < "$xsels/${clip%% *}";
        fi;
};

typeset -i \
    OPTIND=1 \
    OPTERR=1;

typeset \
    opt= \
    opt_board=false \
    opt_clear=false \
    opt_daemon=false \
    opt_kill=false \
    opt_restart=false \
    xsels=${XDG_RUNTIME_DIR:?}/clipbuffer;

while
    getopts :bcdkr opt;
do
    case $opt in
        (b)
            opt_board=:;;
        (c)
            opt_clear=:;;
        (d)
            opt_daemon=:;;
        (k)
            opt_kill=:;;
        (r)
            opt_restart=:;
    esac;
done;

if
    $opt_daemon;
then
    Clipbuffer::Daemon;
elif
    $opt_kill;
then
    Clipbuffer::Kill;
elif
    $opt_restart;
then
    Clipbuffer::Kill;
    [[ -n $DISPLAY ]] &&
        daemonize "$BASH_SOURCE" -d;
else
    Clipbuffer::Clip;
fi;

# vim: set ts=4 sw=4 tw=0 et :
