#!/bin/sh
#
# Wrapper: Confluence REST API.

. "$(which rest-api)" ||
    exit;

server_address=${CONFLUENCE_SERVER_ADDRESS:-https://confluence.wir.invalid};

unset -v CONFLUENCE_SERVER_ADDRESS;

get() {
	case $endpoint in
		(space)
			endpoint=/rest/api/$endpoint?limit=500;;
	esac;

	\curl;
}

\main "$@";

# vim: set ft=sh :
