#!/usr/bin/env bash
#
# Visually count down time.
#
# Source: http://askubuntu.com/questions/16149/\
#       overwrite-previous-output-in-bash-instead-of-appending-it

printf -v sec %d "$1" ||
    exit 1
SECONDS=0

while command -- sleep .5 && ((SECONDS <= sec)); do
    printf "\r%0${#sec}d" "$((sec - SECONDS))"
done

printf \\n

# vim: set ft=zsh :
