#!/usr/bin/env bash
#
# Countdown.
# Source: http://askubuntu.com/questions/16149/ \
#       overwrite-previous-output-in-bash-instead-of-appending-it

sec=$1
SECONDS=0

while
        sleep .5 && (( SECONDS <= sec ));
do
        printf "\r%0${#sec}d" "$(( sec - SECONDS ))"
done

printf '\n'

# vim: set ts=8 sw=8 tw=0 et :
