#!/usr/bin/env bash
#
# Test against daytime and adjust my config.

typeset -i FORCE=$FORCE;
f=${XDG_CACHE_HOME:?}/DAYLIGHT;

if
    test-daylight;
then
    [[ -f $f && FORCE -eq 0 ]] || {
        > "$f";
        exec theme light;
    };
else
    [[ -f $f || FORCE -gt 0 ]] && {
        rm -f -- /tmp/DAYLIGHT;
        exec theme dark;
    };
fi;

:;

# vim: set ts=4 sw=4 tw=0 et :
