#!/bin/sh
#
# Test against daytime and adjust my config.

f=${XDG_RUNTIME_DIR:?}/DAYLIGHT;

light ()
case $1 in
(0)
    : > "$f";
    exec theme light;;
(*)
    rm -f -- "$f";
    exec theme dark;;
esac;

case $1 in
(dark)
    light;;
(light)
    light 0;;
(*)
    test-daylight;
    light $?;;
esac;


# vim: set ft=sh :
