#!/bin/sh
#
# Build /etc/apt/sources.list with the help of netselect-apt.

test "$(command id -u)" -ne 0 && {
	echo 'damn. invoke me as root, please' 1>&2;
	exit 1;
};

cd /tmp ||
	exit 1;

command cp -fv /etc/apt/sources.list /etc/apt/sources.list.old;
command cp -fv /etc/apt/preferences /etc/apt/preferences.old;
command rm -frv /tmp/napt;

trap exit\ 1 INT TERM QUIT;

for release in stable #testing unstable experimental;
do
	command mkdir -p "/tmp/napt/$release";

	i=0
	while
		test "$i" -le 2;
	do
		command netselect-apt -t 10 "$release" > "/tmp/napt/$release/$i";
		i=$((i + 1));
	done;

	server=$(
		grep -o -h 'https\?.*$' "/tmp/napt/$release/"?* |
		sort |
		uniq -cd |
		tac | {
			read -r _ l;
			printf '%s' "$l";
		}
	);
	case $release in
		(stable|bullseye)
			command cat >> "/tmp/napt/01-$release-source.list" <<-IN
				#
				# $release
				#
				#deb $server $release main contrib non-free
				#deb-src $server $release main contrib non-free
				#
				# $release-updates
				#
				#deb $server $release-updates main contrib non-free
				#deb-src $server $release-updates main contrib non-free
				#
				# $release-security
				#
				#deb http://security.debian.org/ $release-security main contrib non-free
				#deb-src http://security.debian.org/ $release-security main contrib non-free
				#
				# $release-backports
				#
				#deb $server $release-backports main contrib non-free
				#deb-src $server $release-backports main contrib non-free
				#
				# $release-debug
				#
				#deb http://debug.mirrors.debian.org/debian-debug/ $release-debug main
				#
			IN
			;;
		(testing)
			command cat >> "/tmp/napt/02-$release-source.list" <<-IN
				#
				# $release
				#
				#deb $server $release main contrib non-free
				#deb-src $server $release main contrib non-free
				#
				# $release-security
				#
				#deb http://security.debian.org/ $release-security main contrib non-free
				#deb-src http://security.debian.org/ $release-security main contrib non-free
				#
				# $release-debug
				#
				#deb http://debug.mirrors.debian.org/debian-debug/ $release-debug main
				#
			IN
			;;
		(unstable)
			command cat >> "/tmp/napt/03-$release-source.list" <<-IN
				#
				# $release
				#
				#deb $server $release main contrib non-free
				#deb-src $server $release main contrib non-free
				#
				# $release-debug
				#
				#deb http://debug.mirrors.debian.org/debian-debug/ $release-debug main
				#
			IN
			;;
		(experimental)
			command cat >> "/tmp/napt/04-$release-source.list" <<-IN
				#
				# $release
				#
				#deb $server $release main contrib non-free
				#deb-src $server $release main contrib non-free
				#
				# $release-debug
				#
				#deb http://debug.mirrors.debian.org/debian-debug/ $release-debug main
				#
			IN
			;;
		(*)
			printf 'unknown release: %s\n' "$release" 1>&2;
			exit 1;
			;;
		esac
done;

command cat /tmp/napt/*-source.list > /etc/apt/sources.list;

command cat > /etc/apt/preferences <<-IN
		# Package: *
		# Pin: release a=stable
		# Pin-Priority: 700

		# Package: *
		# Pin: release a=testing
		# Pin-Priority: 650

		# Package: *
		# Pin: release a=unstable
		# Pin-Priority: 600
	IN

# vim: set ft=sh :
