#!/usr/bin/env bash
#
# Disown job.

set -o monitor;

"${1:?}" "${@:2}" &
pid=$!;

jn=$(
    jobs -lr |
    sed "/\[[0-9]*\]+ ${pid}/ s/\[\([0-9]*\)\].*/\1/";
);

((jn)) &&
    builtin disown "%$jn";

# vim: set ts=4 sw=4 tw=0 et :
