#!/bin/sh
#
# Backup all urls from dnsmasq log.

file=urls.log
log=${XDG_VAR_HOME:-/home/user1/var}/log/$file
command -- touch -- "$log"

exec grep -F -e ' reply ' /var/log/dnsmasq.log |
    exec grep -F -v -e CNAME -e NXDOMAIN -e NODATA |
    exec cut -d ' ' -f 6 |
    exec /home/user1/bin/grep-url |
    exec cat -- "$log" - |
    exec sort -u >"/tmp/$file.$$"

test -s "/tmp/$file.$$" &&
    command -- mv -- "/tmp/$file.$$" "$log" &&
    exec chmod 755 "$log"

# vim: set ft=sh :
