#!/bin/sh
#
# Disk usage of unlinked, but still open files.
#
# Source: http://chneukirchen.org/dotfiles/bin/dudel

exec find -L /proc/*/fd -maxdepth 1 -type f -links 0 -printf '%b %p\n' 2>/dev/null |
    while IFS=' ' read -r size fd; do
        pid=${fd#/proc/}
        pid=${pid%/fd/*}
        prog=$(exec readlink -- "/proc/$pid/exe")
        prog=${prog##*/}
        printf '%-10d %-10s %-20s %s\n' "$size" "$prog" "$fd" "$(exec readlink -- "$fd")"
    done |
    exec sort -r

# vim: set ft=sh :
