#!/bin/sh
#
# Add a task to Taskwarrior ('event' context) via vim (yaml).

export TASKRC=$XDG_CONFIG_HOME/taskwarrior/taskrc-event;

eval "$(date +'s=%s d=%Y-%m-%d t=%H:%M')";
f=${TMPDIR:-${XDG_RUNTIME_DIR}/tmp}/$s.task;

trap 'rm "$f"' EXIT;

cat > "$f" <<-TEMPLATE
	%YAML 1.1
	---
	description:

	entry: now
	# scheduled: ${d}_00:00
	# due: ${d}_00:00
	# until: ${d}_00:00

	# recur:

	tags:
	    - event
	...
TEMPLATE

vim -f \
 '+set ft=yaml' \
 +3 \
 "+startinsert!" \
 "$f" < /dev/tty > /dev/tty;

yaml2json < "$f" |
jq 'if (.description | length) > 0 then . else empty end' |
task import -;

# vim: set ft=sh :
