#!/bin/sh
#
# Select feed url via dmenu and use it in newsboat.

cache=${XDG_VAR_HOME:?}/lib/feedfaetcher/cache
tagfile=${XDG_CONFIG_HOME:?}/newsboat/tags
feedfile=$XDG_CONFIG_HOME/newsboat/urls

feed=$(
    exec find -H "$cache" -type f |
        exec menu dmenu2 FEED
)

tags=$(
    exec grep -v -e '^"_Filter' -- "$tagfile" |
        exec menu dmenu2 TAGS
)

if test -n "$tags"; then
    printf 'file://%s %s\n' "$feed" "$tags" >>"$feedfile"
else
    printf 'No tag has been chosen\n' 1>&2
fi

# vim: set ft=sh :
