#!/bin/sh
#
# Wrapper: feedfaetcher.

feedcacherdir=${XDG_VAR_HOME:?}/lib/feedfaetcher;
urllist=$feedcacherdir/urls.txt;

mkdir -p "$feedcacherdir";

if
	test -n "$1"
then
	<<< "$1" cat -- "$urllist" - |
		sort -u > "$urllist.$$" &&
		mv -- "$urllist.$$" "$urllist";
else
	exec feedfaetcher;
fi;

# vim: set ft=sh :
