#!/bin/sh
#
# Wrapper: firefox

r=${XDG_CACHE_HOME:?}/firefoxw;

test -r "$r" -a -n "$force_new" && {
    t=$(mktemp -d);
    rsync -var --delete "$t/" "$r/";
    rm -rf -- "$t";
};

test -r "$r/"user.js || {
    mkdir -p -- "$r/cache";
    cat > "$r/"user.js <<!
user_pref("accessibility.browsewithcaret", true);
user_pref("accessibility.force_disabled", 1);
user_pref("app.normandy.first_run", false);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "custom");
user_pref("browser.download.dir", "/home/files/tmp/downloads");
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.fixup.dns_first_for_single_words", true);
user_pref("browser.link.open_newwindow", 3);
user_pref("browser.link.open_newwindow.restriction", 2);
user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr.addons", false);
user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr.features", false);
user_pref("browser.newtabpage.activity-stream.feeds.section.highlights", false);
user_pref("browser.newtabpage.activity-stream.feeds.snippets", false);
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);
user_pref("browser.newtabpage.activity-stream.prerender", false);
user_pref("browser.newtabpage.activity-stream.section.highlights.includeBookmarks", false);
user_pref("browser.newtabpage.activity-stream.section.highlights.includeDownloads", false);
user_pref("browser.newtabpage.activity-stream.section.highlights.includePocket", false);
user_pref("browser.newtabpage.activity-stream.section.highlights.includeVisited", false);
user_pref("browser.newtabpage.activity-stream.showSearch", false);
user_pref("browser.newtabpage.enabled", false);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.introShown", false);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.pocket.enabled", false);
user_pref("browser.preferences.advanced.selectedTabIndex", 4);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.enabled", false);
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.search.hiddenOneOffs", "Wikipedia (en)");
user_pref("browser.search.suggest.enabled", false);
user_pref("browser.search.update", false);
user_pref("browser.startup.page", 0);
user_pref("browser.tabs.animate", false);
user_pref("browser.tabs.closeWindowWithLastTab", false);
user_pref("browser.tabs.closeWindowWithLastTab", true);
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.suggest.bookmark", false);
user_pref("browser.urlbar.suggest.openpage", false);
user_pref("datareporting.healthreport.service.enabled", false);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1450604664862");
user_pref("datareporting.policy.firstRunTime", "1450604654097");
user_pref("devtools.onboarding.telemetry.logged", false);
user_pref("dom.apps.reset-permissions", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pocket.enabled", false);
user_pref("general.warnOnAboutConfig", false);
user_pref("layout.spellcheckDefault", 0);
user_pref("loop.enabled", false);
user_pref("media.eme.enabled", true);
user_pref("network.cookie.cookieBehavior", 3);
user_pref("network.cookie.lifetimePolicy", 2);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.predictor.cleaned-up", true);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("pdfjs.disabled", true);
user_pref("pdfjs.enabledCache.state", false);
user_pref("permissions.default.camera", 2);
user_pref("permissions.default.geo", 2);
user_pref("permissions.default.microphone", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("pref.downloads.disable_button.edit_actions", false);
user_pref("pref.privacy.disable_button.cookie_exceptions", false);
user_pref("privacy.clearOnShutdown.offlineApps", true);
user_pref("privacy.clearOnShutdown.siteSettings", true);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.history.custom", true);
user_pref("privacy.sanitize.didShutdownSanitize", true);
user_pref("privacy.sanitize.migrateClearSavedPwdsOnExit", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.sanitize.sanitizeOnShutdown", true);
user_pref("privacy.trackingprotection.cryptomining.enabled", true);
user_pref("privacy.trackingprotection.enabled", true);
user_pref("privacy.trackingprotection.fingerprinting.enabled", true);
user_pref("signon.importedFromSqlite", true);
user_pref("signon.rememberSignons", false);
!
};

export XDG_CACHE_HOME=$r/cache;

exec firefox \
    --profile "$r" \
    ${1:+"$@"};

# vim: set ft=sh :
