#!/usr/bin/env bash
#
# Simple replacement for urlview using fzf in X.
#
# Usage:
#
# $ furlview FILE1 ... FILEn
# $ foo | furlview
# $ furlview < FILE
# $ furlview <<< "foo"
# $ furlview <<URIS
## foo
## URIS
#
# FILE is regular or piped, that is also <(foo)


test-xorg ||
	exit 1;

function __x_web_browser {
	setsid -f x-web-browser "$1";
};

function __fzf {
	fzf --tac -e -i -m;
};

function __ugrep {
	grep-urls;
};

function __select {
	__ugrep |
	__fzf;
};

function __is_file [[ -p $1 || -f $1 ]];

if
	__is_file /dev/stdin;
then
	mapfile -t furls < <(__select);
else
	(($#)) || {
		printf %s\\n aaarg? 1>&2;
		exit 1;
	};
	mapfile -t furls < <(
		for a in "$@";
		do
			if
				__is_file "$a";
			then
				cat -- "$a";
			else
				printf \
					"File '%s' is neather a regular file nor a named pipe, that is executable\n" \
					"$a" 1>&2;
			fi;
		done |
		__select;
	);
fi;

for u in "${furls[@]}";
do
	__x_web_browser "$u" &
done;

wait;

# vim: set ft=sh :
