#!/usr/bin/env bash
#
# Simple replacement for urlview using fzf in X.
#
# Usage:
#
# $ furlview FILE1 ... FILEn
# $ foo | furlview
# $ furlview < FILE
# $ furlview <<< "foo"
# $ furlview <<URIS
## foo
## URIS
#
# FILE is regular or piped, that is also <(foo)

command -- test-xorg ||
    exit 1

function __select {
    exec -- grep-url |
        exec -- fzf --tac -e -i -m
}

function __is_file [[ -p $1 || -f $1 ]]

if __is_file /dev/stdin; then
    mapfile -t furls < <(__select)
else
    if ! (($#)); then
        echo Error: Missing arguments 1>&2
        exit 1
    fi

    mapfile -t furls < <(
        for f in "$@"; do
            if __is_file "$f"; then
                command -- cat -- "$f"
            else
                printf \
                    "Error: File '%s' is neather a regular file nor a named pipe\n" \
                    "$f" 1>&2
            fi
        done |
            __select
    )
fi

for u in "${furls[@]}"; do
    command -- daemonize run-chromium "$u" &
done

wait

# vim: set ft=zsh :
