#!/bin/sh
#
# Get sun data infos from www.gaisma.com.

exec curl -s https://www.gaisma.com/en/location"/${1:-${X_MY_LOCATION1:?}}."html |
    exec scrape -be table.sun-data |
    exec w3m -dump -T text/html |
    exec head

# vim: set ft=sh :
