#!/bin/sh
#
# Get md5sum of /sys/devices/virtual/dmi/id/product_name.

comp=$(exec cat /sys/devices/virtual/dmi/id/product_name)
comp=$(printf %s "$comp" | exec md5sum)

echo "${comp%  -}"

# vim: set ft=sh :
