#!/bin/sh
#
# Bitbucket REST API: Get all open wir prs.

cache=${TMPDIR:-/tmp}/get-all-open-wir-prs;
export cache;

mkdir -p "$cache";
rm -r "$cache/"*;

bitbucket-rest-api get repos 2>/dev/null |
jq -r --unbuffered '
	.values[] |
	select(.project.key | contains("~") | not) |
	.project.key, .slug
' |
xargs -L 1 -n 2 -P 0 sh -c '
	bitbucket-rest-api get \
		"/rest/api/latest/projects/$1/repos/$2/pull-requests?state=open&limit=999" \
		2>/dev/null |
	jq -rc "select((.values | length) > 0)" > "$cache/$1-$2";
' --;

cat "$cache"/* |
jq -rc '[inputs]';

# vim: set ft=sh :
