#!/bin/sh
#
# Get concubium and gallicinium.

set -- $(get-sundata 2>/dev/null) $(get-sundata "$(date --date=tomorrow +%s)");
set -- ${3%:*}h ${3#*:}min ${2%:*}h  ${2#*:}min;

q=$(calculate-date "
	(
		(tomorrow + $1 + $2)
		- (today + $3 + $4)
	)/4
");

echo concubium "$(calculate-date "today + $3 + $4 + $q")";
echo gallicinium "$(calculate-date "tomorrow + $1 + $2 - $q")";

# vim: set ft=sh :
