#!/bin/sh
#
# Bitbucket REST API: Get all repo hrefs.

p=http;
case $1 in
	(http|ssh)
		p=$1;;
esac;

bitbucket-rest-api get repos |
jq -rc --arg p "$p" '
	.values[].links.clone[] |
	select((.name | contains($p)) and (.href | contains("~") | not)) |
	.href
';

# vim: set ft=sh :
