#!/bin/sh
#
# Show network connections.

if
    test-inet;
then
    printf 'WAN-IP: %s\n' "$(
        w3m -dump http://ip-check.info/\?lang=en |
        grep -F -A 2 IP\ check |
        tail -n 1;
    )";
else
    printf 'WAN-IP: offline\n';
fi;

ip a show wlan0 |
mawk '/inet/ { print $0 }';

echo;
sudo netstat -tapen;
echo;
lsof -i :1-10000;
echo;

# vim: set ts=4 sw=4 tw=0 et :
