#!/usr/bin/env php
<?php
    // Get sunrise and sunset.
    // Idea: https://github.com/baskerville/bin/blob/macosx/daytime

    if ($argc == 2) {
        $now = $argv[1];
    }
    if (empty($now)) {
        $now = time();
    }

    $latitude = getenv('X_MY_LATITUDE1');
    $longitude = getenv('X_MY_LONGITUDE1');
    $offset = (new \DateTimeImmutable('now', new \DateTimeZone(getenv('TZ'))))
        ->getOffset() / 3600;

    $sunrise = \date_sunrise(
        $now,
        \SUNFUNCS_RET_TIMESTAMP,
        $latitude,
        $longitude,
        90.583333,
        $offset
    );
    $sunset = \date_sunset(
        $now,
        \SUNFUNCS_RET_TIMESTAMP,
        $latitude,
        $longitude,
        90.583333,
        $offset
    );

    print strftime('%H:%M', $sunrise) . ' ' . strftime('%H:%M', $sunset) . PHP_EOL;

    if ($sunrise < $now && $now < $sunset) {
        exit(0);
    } else {
        exit(1);
    }

// vim: set ft=php :
