#!/bin/sh
#
# Jira REST API: Get all my mate's jira issues.

mates=${1:-t630};

exec jira-rest-api get \
	"/rest/api/2/search?maxResults=999&jql=assignee%20IN%20($mates)%20and%20resolution=Unresolved"

# vim: set ft=sh :
