#!/bin/sh
#
# Get sun data infos from http://www.gaisma.com.

echo;

curl -s http://www.gaisma.com/en/location/"${1:-$X_MY_LOCATION1}".html |
scrape -be 'table.sun-data' |
w3m -dump -T text/html |
head;

# vim: set ts=4 sw=4 tw=0 et :
