#!/bin/sh
#
# Get concubium and gallicinium.

set -f
IFS=' '
set -- $(exec get-sundata 2>/dev/null) $(exec get-sundata "$(exec date --date=tomorrow +%s)")
set -- ${3%:*}h ${3#*:}min ${2%:*}h ${2#*:}min

q=$(exec task-calc "((tomorrow + $1 + $2) - (today + $3 + $4)) / 4 ")

printf '%s %s\n' \
    "$(exec task-calc "today + $3 + $4 + $q")" \
    "$(exec task-calc "tomorrow + $1 + $2 - $q")"

# vim: set ft=sh :
