#!/bin/sh
#
# Bitbucket REST API: Get all open and overdue wir prs.

sec=${1:-$((60*60*24*14))};

get-all-open-wir-prs 2>/dev/null |
jq -rc --arg sec "$sec" '
	[
		.[].values[] |
		select(now - (.updatedDate / 1000) >= ($sec | tonumber))
	]
';
# vim: set ft=sh :
