#!/usr/bin/env dash
#
# Wrapper for getting my news.

if
         exec 9<"$0";
         ! flock -n 9
then
         printf '%s\n' "sorry, I am already running" 1>&2;
         exit 1
fi

if
        ! test-inet
then
        loggi 3 .network.error "We are offline. News have not been updated"
        exit 1
fi

feedfaetcher &
d="$(
        urldiff -nv \
        | fgrep NEW \
        | wc -l;
) unread diffs"

wait
f="$(newsbeuter -rx print-unread)"

test "$((${d%% *} + ${f%% *}))" -ge 0 && loggi 6 .transfer.complete "${d}\n${f}";

# vim: set ts=8 sw=8 tw=0 et :
