#!/bin/sh
#
# Add a task to Taskwarrior ('habit' context) via vim (yaml).

export TASKRC=$XDG_CONFIG_HOME/taskwarrior/taskrc-habit

eval "$(exec date '+s=%s d=%Y-%m-%d t=%H:%M')"
f=${TMPDIR:-${XDG_RUNTIME_DIR}/tmp}/$s.task

trap 'exec rm -- "$f"' EXIT

command -- cat >"$f" <<TEMPLATE
%YAML 1.1
---
description:

# role: me
# opposite: me
# contact: face-to-face
# location: somewhere
# participant: me

entry: now
# due: ${d}_00:00
# scheduled: ${d}_00:00
# wait: ${d}_00:00
# until: ${d}_00:00
# recur:

# depends:
#     -

# project:
# priority:

tags:
    - habit
    - deletable

# annotations:
#     -
#         entry: now
#         description:
...
TEMPLATE

command -- vim -f \
    '+set ft=yaml' \
    +3 \
    '+startinsert!' \
    "$f" </dev/tty >/dev/tty ||
    exit 1

exec yaml2json <"$f" |
    exec jq 'if (.description | length) > 0 then . else empty end' |
    exec task import -

# vim: set ft=sh :
