#!/usr/bin/env bash
#
# Simple ad- and malware-blocking-list builder for dnsmasq.
# Inspired by hostblock (http://gaenserich.github.com/hostsblock)

(($#)) && exec sudo "$(type -P "$0")";

typeset -x \
    hblock_cachedir=${TMPDIR:-/tmp}/hostfiles \
    hblock_tmpdir=${TMPDIR:-/tmp}/hblock;

#hostfile_regular=/etc/hosts.regular
hblock_hlist=/home/user1/etc/hblock/hlist.txt \
hblock_black=/home/user1/etc/hblock/black.txt \
hblock_white=/home/user1/etc/hblock/white.txt \
hostfile_block=/etc/hosts.block;

function __hblock_do {
    typeset outfile=${1//http:\/\//};
    outfile=${outfile//[\/\%\&\+\?\=\\]/\.};

    wget --no-verbose \
        --connect-timeout=3 \
        --content-on-error \
        --dns-timeout=3 \
        --ignore-length \
        --inet4-only \
        --no-cache \
        --no-cookies \
        --no-http-keep-alive \
        --read-timeout=3 \
        --tries=1 \
        -O - \
        "$1" |
    tee "${hblock_cachedir}/${outfile}.dirty" |
    sed -rn '
        /^(0.0.0.0|127.0.0.1)/ {
            s/^127.0.0.1/0.0.0.0/;
            s/[[:space:]][[:space:]]*/ /g;
            s/[[:space:]]$//;
            s/^$//;
            s/^#.*//;
            p
        }' > "${hblock_tmpdir}/${outfile}.clean";
};

typeset -xf __hblock_do;
trap "{ rm -fr -- "$hblock_tmpdir"; exit 0; };" INT TERM QUIT EXIT;
mkdir -p -- "$hblock_cachedir" "$hblock_tmpdir";

## Do the thing.
xargs \
    -a "$hblock_hlist" \
    -n 1 \
    -P 8 \
    -i bash -c '__hblock_do "$@"' _ {};

cat "$hblock_black" <(
    echo;
    echo;

    sort -u "${hblock_tmpdir}/"*.clean |
    egrep -v -f "$hblock_white";
) > "$hostfile_block";

chmod 644 "$hostfile_block" "/etc/resolv-dnsmasq.conf";
rm -f "/var/run/dnsmasq/resolv.conf" "/run/dnsmasq/resolv.conf";

systemctl restart dnsmasq;

# vim: set ts=4 sw=4 tw=0 et :
