#!/bin/sh
#
# Wrapper: Default highlighting tool.

for f; do
    /usr/bin/source-highlight \
        --failsafe \
        --infer-lang \
        -f esc-solarized \
        --outlang-def"=$XDG_DATA_HOME/"source-highlight/solarized/esc-solarized.outlang \
        --style-file"=$XDG_DATA_HOME/"source-highlight/solarized/esc-solarized.style \
        -o STDOUT \
        --tab=4 \
        --line-number=0 \
        -i "$f";
    echo;
done;

tput sgr0;

# vim: set ts=4 sw=4 tw=0 et :
