#!/bin/sh
#
# Wrapper: imapfilter with config localhost-delete.lua.

exec imapfilter \
	-c "$HOME/".imapfilter/localhost-delete.lua \
	-l "${XDG_VAR_HOME:?}/"log/imapfilter.log;

# vim: set ts=4 sw=4 tw=0 noet :
