#!/usr/bin/env bash
#
# Log WAN IP.

log=${XDG_VAR_HOME:?}/log/ip-log.log
to=ip-log
subject=ip-log

printf '%(%Y-%m-%d_%R)T %s\n' -1 "$(exec -- get-wan-ip)" |
    exec -- tee -a "$log" |
    exec -- mailx -s "$subject" "$to"

# vim: set ft=zsh :
