#!/bin/sh
#
# Add a task into Taskwarrior ('issue' context) via vim (yaml).

export TASKRC=$XDG_CONFIG_HOME/taskwarrior/taskrc-issue;

eval "$(date +'s=%s d=%Y-%m-%d t=%H:%M')";
f=${TMPDIR:-${XDG_RUNTIME_DIR}/tmp}/$s.task;

trap 'rm "$f"' EXIT;

cat > "$f" <<-TEMPLATE
	%YAML 1.1
	---
	description:

	priority: L
	origin: mind
	# due: ${d}_${t}
	...
TEMPLATE

vim -f \
 '+set ft=yaml' \
 +3 \
 "+startinsert!" \
 "$f" < /dev/tty > /dev/tty;

yaml2json < "$f" |
jq 'if (.description | length) > 0 then . else empty end' |
task import -;

# vim: set ts=2 sw=2 tw=0 noet :
