#!/bin/sh
#
# Wrapper: Jira REST API.

server_address=${JIRA_SERVER_ADDRESS:-https://jira.wir.invalid};

unset -v JIRA_SERVER_ADDRESS;

. "$(which rest-api)" ||
    exit;

\main "$@";

# vim: set ft=sh :
