#!/bin/sh
#
# Simple notetaker using rlfe.

store=${XDG_DATA_HOME:-${HOME}/.local/share}/kuno2
date=$(date --utc --date now +%s)

mkdir -p -- "$store"
rlfe -h "${store}/${date}" cat

# vim: set ts=8 sw=8 tw=0 et :
