#!/bin/sh
#
# My preprocessor for less.

test $# -gt 0 ||
    exit 1;

trap exit\ 0 PIPE;
umask 077;
space=' ' \
tab='	' \
newline='
' \
LESSMETACHARS="$space$tab$newline'"';*?"()<>[|&^`#\$%=~';
export LESSMETACHARS;

test -x "$HOME/".lessfilter &&
    "$HOME/".lessfilter "$1" &&
        exit 82;

for i in $LESSIGNORE; do
    case $1 in
        (*.$i)
            exit 82;;
    esac;
done;

if
    test "${LESSCOLOR:-0}" -eq 2 ||
        case $LESS in
            (*-[rR]*)
                :;;
            (*)
                ! :;;
        esac;
then
    open -A cdog -A about -f "$1" 2>&1;
else
    open -A dog -A about -f "$1" 2>&1;
fi;

# vim: set ft=sh :
