#!/bin/sh
#
# List all user presences in Rocket.Chat.

rocketchat-rest-api get users.presence 2>/dev/null |
jq -r '
	.users[] |
	"\(.name)\t\(.username)\t\(.status)\t\(.statusText)"
' |
sort |
column -t -s '	';

# vim: set ft=sh :
