#!/bin/sh
#
# List all rocketchat channels I haven't joined yet.

joined=$(
	rocketchat-rest-api get channels.list.joined 2>/dev/null |
	jq -rc '.channels | map({(._id): null}) | add'
);

rocketchat-rest-api get channels.list 2>/dev/null |
jq -r --argjson joined "$joined" '
	.channels[] |
	._id as $_id |
	select($joined | has($_id?) | not) |
	"\(.name)\t\(.u.username)\t\(.ts)"
' |
sort -s -k 3,3 |
column -t;

# vim: set ft=sh :
