#!/bin/sh
#
# Manually lock screen.

if command -- test-xorg; then
    exec xorg-lock
else
    command -- fgconsole 1>/dev/null 2>&1 ||
        exit 1
    case $TERM in
        linux*)
            exec physlock -m
            ;;
    esac
fi

# vim: set ft=sh :
