#!/bin/sh
#
# Wrapper: Use taskwarrior in my 'log' context.

export TASKRC=$XDG_CONFIG_HOME/taskwarrior/taskrc-todo

exec 2>/dev/null

command -- task context log >/dev/null
trap 'exec task context none >/dev/null' EXIT

command -- task +log +todo "$@"

# vim: set ft=sh :
