#!/bin/sh
#
# Wrap up logger for local scripting.
# Needs facility local6 to work properly with my configured rsyslog.
#
# $ loggi level category [summary [body]]

l="$1" \
c="$2" \
prog=;

shift 2;

logger -d -s --id="$PPID" \
    -t "$(basename "$(strings /proc/${PPID}/cmdline)")" \
    -p "local6.${l}" -s "$c" "$@";

# vim: set ts=4 sw=4 tw=0 et :
