#!/bin/sh
#
# Wrap up logger for local scripting.
# Needs facility local6 to work properly with my configured rsyslog.
#
# $ loggi level category [summary [body]]

l=$1 \
c=$2;

shift 2;

logger -d -s --id=$PPID \
    -t "$(basename "$(strings /proc/$PPID/cmdline)")" \
    -p local6".$l" "$c" "$@";

# vim: set ft=sh :
