#!/usr/bin/env bash
#
# Send mail via msmtp-queue and give notification + sound.

exec 9<"$0";
flock -n 9 || {
    printf 'sorry, I am already running\n' 1>&2;
    exit 1;
};

maildir=${XDG_VAR_HOME:?}/mail/queue;
[[ -d $maildir ]] || {
    printf "maildir '%s' is not a directory\n" "$maildir" 1>&2;
    exit 1;
};

shopt -s nullglob;
shopt -s extglob;
shopt -s dotglob;
set -- "$maildir/"!(\.*);

(($#)) &&
    cnt=$# ||
        exit 1;

i=0;
until
    ! (($#));
do
    case $i in
        (30)
            loggi 3 .email.error 'Delivery error. [posteo] Mails not sent: '"$cnt";
            exit 1;;
        (*)
            msmtp-queue -r;
            set -- "$maildir/"!(\.*);
            ((i++));
            sleep 1;
    esac;
done;

loggi 6 .email.bounced '[posteo] Sent Mails: '"$cnt";

# vim: set ts=4 sw=4 tw=0 et :
