#!/usr/bin/env bash
#
# Get mail and give notification + sound.

if
         exec 9<"$0";
         ! flock -n 9
then
         printf '%s\n' "sorry, I am already running" 1>&2;
         exit 1
fi

mpop -a >> "${XDG_VAR_HOME}/log/mpop.log" 2>&1;

mapfile -t reply < <(
        imapfilter \
                -c "${HOME}/.imapfilter/localhost.lua" \
                -l "${XDG_VAR_HOME}/log/imapfilter.log";
)

((${reply[0]//[!0-9]/} + ${reply[1]//[!0-9]/} > 0)) || exit 1;
loggi 6 .email.arrived "${reply[0]:-?}\n${reply[1]:-?}"

# vim: set ts=8 sw=8 tw=0 et :
