#!/usr/bin/env bash
#
# Send mail via msmtp-queue and give notification + sound.

if
         exec 9<"$0";
         ! flock -n 9
then
         printf '%s\n' "sorry, I am already running" 1>&2;
         exit 1
fi

maildir=${XDG_VAR_HOME}/mail/queue
if
        ! [[ -d $maildir ]]
then
        printf "maildir '%s' is not a directory\n" "$maildir" 1>&2;
        exit 1
fi

shopt -s nullglob
shopt -s extglob
shopt -s dotglob
set -- "${maildir}/"!(\.*)

(($#)) && cnt=$# || exit 1;

i=0
until
        (( ! $# ))
do
        case $i in
        30)
                printf -v msg '[posteo] Mails not sent: %d\n' "$cnt"
                if
                        [[ -n $DISPLAY ]]
                then
                        notify-send --category=email.error \
                                "email.error: Mail fetch error" "$msg";
                else
                        sound _ "email.error:"
                        printf 'Mail fetch error:\n%s\n' "$msg" 1>&2;
                fi
                exit 1
        ;;
        *)
                msmtp-queue -r
                set -- "${maildir}/"!(\.*)
                ((i++))
                sleep 1
        esac
done

msg="[posteo] Sent Mails: ${cnt}"
if
        [[ -n $DISPLAY ]]
then
        notify-send --category=email.bounced -u normal "email.bounced:" "$msg"
else
        sound _ "email.bounced:"
        printf 'Mail bounced:\n%s\n' "$msg" 1>&2;
fi

# vim: set ts=8 sw=8 tw=0 et :
