#!/bin/sh
#
# Update mail dirs.

if
    test-inet;
then
    mail-send &
    #mail-hook-pre
    mail-get;
    #mail-hook-post
else
    run-logger 3 .network.error 'We are offline. Mails have not been updated';
    exit 1;
fi;

wait;

# vim: set ft=sh :
