#!/usr/bin/env dash
#
# MediathekView (german tv)

case "$1" in
run)
        java -jar /opt/MediathekView.jar
        ;;
load)
        java -jar /opt/bin/MediathekView.jar -auto -noGui
        ;;
*)
        printf '%s\n' "Usage: mediathekieww (run|load)" 1>&2;
        exit 1
esac

#  vim: set ts=8 sw=8 tw=0 et :
