#!/bin/sh
#
# A wrapper script for selecting "menu driven" programs.

menu=${1:?};
menu_prompt=$2;

fn=monospace:size=9;

color () {
	if
		test -f "${XDG_RUNTIME_DIR:?}/DAYLIGHT";
	then
		nb=\#FDF6E3; # base3
		nf=\#657B83; # base00
		sb=\#EEE8D5; # base2
		sf=\#B58900; # yellow
		uc=\#B58900; # yellow
	else
		nb=\#002B36; # base03
		nf=\#839496; # base0
		sb=\#073642; # base02
		sf=\#859900; # green
		uc=\#859900; # green
	fi;
};

case $menu in
	(choose)
		exec choose -;;
	(dmenu)
		color;
		exec dmenu -b -i \
			-fn "$fn" \
			-l 10 \
			-nb "$nb" \
			-nf "$nf" \
			-p "${menu_prompt:->}";;
	(dmenu2)
		exec dmenu2 -b -i \
			-class dmenu2 \
			-fn "$fn" \
			-l 10 \
			-name dmenu2 \
			-p "${menu_prompt:->}";;
	(dmenu2-save)
		exec dmenu2 -b -f \
			-class dmenu2-save \
			-fn "$fn" \
			-mask \
			-name dmenu2-save \
			-noinput \
			-p "${menu_prompt:-*}";;
	(slmenu)
		exec slmenu -b -i -p "${menu_prompt:->}";;
	(fzf)
		exec fzf -x -i +s --prompt="${menu_prompt:->} ";;
	(fzf-print-query)
		exec fzf -x -i +s --prompt="${menu_prompt:->} " --print-query;;
esac;

# vim: set ft=sh :
