#!/bin/sh
#
# Configure monitor(s): xrandr, screen blanking, DPMS.

if
	test-xorg;
then
	echo X_DPI=96 audio=\;export X_DPI;

	case ${PRODUCT_NAME_SUM:=$(get-product-name-by-md5sum)} in
		(dd791b3dd44b647e91524123fa1c6d0f)
			if
				xrandr --listmonitors |
				grep -F -q HDMI-1;
			then
				xrandr \
					--output HDMI-1 --dpi 96 --auto \
					--output eDP-1 --off;
				echo audio=HDMI;
			else
				xrandr \
					--output eDP-1 --dpi 96 --mode 1920x1080 --rate 60.01 \
					--output HDMI-1 --off;
				echo audio=PCH;
			fi;

		(1cca3393c5c595d3236c7ad1bd16f0a4)
			xrandr --listmonitors |
			grep -F -q DP-4 &&
				xrandr --output DP-4 --primary --mode 1920x1080 --rotate normal;

			xrandr --listmonitors |
			grep -F -q DP-5 &&
				xrandr --output DP-5 --mode 1920x1080 --rotate normal --right-of DP-4;
	esac;

	xset s 3600 60;
	xset dpms 0 0 0 -dpms;

else
	test -t 1 && fgconsole 1>/dev/null 2>&1 ||
		exit 1;

	case $TERM in
		(linux*)
			exec sudo setterm --blank 0 --powerdown 0 --powersave off;
	esac;
fi;

# vim: set ft=sh :
