#!/bin/sh
#
# Save attachements in Mutt.
#
# Source: https://github.com/vain/bin-pub/blob/master/mutt-save-attachments

d=${XDG_TMP_HOME:?}/attachments

command -- mkdir -p -m 755 -- "$d"

command -- ripmime --no-nameless -i - -d "$d"
command -- find "$d" -type f -exec chmod 644 {} +
command -- find "$d" -mindepth 1 -type d -exec chmod 755 {} +

printf 'Saved all attachments to: %s\n' "$d" >&2

# vim: set ft=sh :
