#!/bin/sh
#
# Show network connections.

if
    test-inet;
then
    printf 'WAN-IP: %s\n' "$(
        dig -4 +short whoami.akamai.net @ns1-1.akamaitech.net
    )";
else
    printf 'WAN-IP: offline\n';
fi;

ip a |
mawk '/inet/ { print $0 }';

echo;
sudo netstat -tapen;
echo;
lsof -i :1-10000;
echo;

# vim: set ft=sh :
