#!/bin/sh
#
# Weekly backup with obnam.

ulimit -n 1024;
ulimit -s 8192;

obnam_conf="${HOME}/.obnam.conf" \
obnam_log="${XDG_VAR_HOME:?}/log/obnam.log";

sudo obnam backup --config="$obnam_conf" --lru-size=8192 --upload-queue-size=8192 \
    --exclude=/home/latch/tmp \
    --exclude=/home/latch/var/mirror \
    --exclude="${HOME}/cache" \
    /etc/ \
    /home/ \
    /root/ \
    /var/backups/ \
    /var/mail/ \
    /var/vmail/ \
    /var/www/;

sudo obnam force-lock --config="$obnam_conf";

sudo obnam forget --config="$obnam_conf" --keep=2w;

# vim: set ts=4 sw=4 tw=0 et :
