#!/usr/bin/env bash
#
# Copy password from pass.

if command -- test-ctty; then
    menu=fzf
else
    menu=dmenu2
fi

read -r file < <(
    exec -- find "$HOME/.password-store/" -type f -name \*.gpg -printf %f\\n |
        exec -- sed 's/.gpg$//g' |
        exec -- sort |
        exec -- menu "$menu"
)

if [[ -f $HOME/.password-store/$file.gpg ]]; then
    if [[ $1 == --type ]]; then
        exec -- pass show "$file" |
            exec -- xdotool type --clearmodifiers --file -
    else
        PASSWORD_STORE_CLIP_TIME=10 exec -- pass show -c "$file"
    fi
fi

# vim: set ft=zsh :
