#!/usr/bin/env bash
#
# Remove PDF metadata with pdftk and exiftool.

shopt -s nocaseglob

if [[ -e ./tmp ]]; then
    printf 'There is already a tmp dir.\n' 1>&2
    exit 1
elif [[ -e ./pdf_new ]]; then
    printf 'There is already a pdf_new dir.\n' 1>&2
    exit 1
fi

command -- mkdir ./tmp ./pdf_new
command -- cp ./*.pdf ./tmp

while IFS='' read -d '' -r; do
    filename=$(exec -- basename "$REPLY")

    # remove XMP-Metadata incrementell
    command -- exiftool -all= "$REPLY"

    # then rewrite PDF
    exec -- pdftk "$REPLY" dump_data |
        exec -- sed -r -e 's/^(InfoValue:).*/\1/g' |
        command -- pdftk "$REPLY" update_info - output "./pdf_new/$filename" 2>/dev/null
done < <(exec -- find ./tmp -type f -iname \*.pdf -print0)

exec -- rm -r ./tmp

# vim: set ft=zsh :
