#!/bin/sh
#
# Notify, if battery power is (almost) gone.

c=$(get-battery-capacity);

! {
	test "$c" -ge 0 -a "$c" -le 25 &&
		run-logger 3 .device.error \
			"Battery capacity is only $c%. Go and connect charger!";
};

# vim: set ft=sh :
