#!/bin/sh
#
# Notify, if battery power is (almost) gone.

c=$(exec get-battery-capacity)

! {
    test "$c" -ge 0 -a "$c" -le 25 &&
        command -- run-logger 3 .device.error \
            "Battery capacity is only $c%. Go and connect charger!"
}

# vim: set ft=sh :
