#!/bin/sh
#
# Notify, if power is (almost) gone.

c=$(test-bat) ||
	exit 1;

test "$c" -le 25 &&
	loggi 3 .device.error "Power is very low, ${c}%. Go and connect charger!";

# vim: set ts=2 sw=2 tw=0 noet :
