#!/usr/bin/env python3
#
# Print APT config of a single file.

import apt_pkg
import sys


if __name__ == "__main__":
    if len(sys.argv) >= 2:
        cnf = apt_pkg.Configuration()
        apt_pkg.read_config_file(cnf, sys.argv[1])
        print(cnf.dump())

# vim: set ft=python :
