#!/usr/bin/env python3
#
# Pick color code.

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

w = Gtk.ColorSelectionDialog(title="color")
w.show()
w.connect("destroy", Gtk.main_quit)
Gtk.main()

# vim: set ft=python :
