#!/usr/bin/env python3
#
# Display fonts.

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

w = Gtk.FontSelectionDialog(title="font")
w.show()
w.connect("destroy", Gtk.main_quit)
Gtk.main()

# vim: set ft=python :
