#!/bin/sh
#
# Reconfigure monitor(s)
#
# xrandr, screen blanking, DPMS.

if command -- test-xorg; then
    echo X_DPI=96 audio=\;export X_DPI

    : "${XDG_CONFIG_HOME:?}" "${PRODUCT_NAME_SUM:=$(exec get-product-name-as-sha256sum)}"

    exec get-edid-as-sha256sums |
        {
            args=
            native=
            plug=

            while IFS= read -r sum; do
                if test -r "$XDG_CONFIG_HOME/computer/$PRODUCT_NAME_SUM/monitor/$sum-port-randr"; then
                    native=$sum
                elif test -r "$XDG_CONFIG_HOME/computer/$PRODUCT_NAME_SUM/monitor/plug/$sum-port-randr"; then
                    if test -r "$XDG_CONFIG_HOME/computer/$PRODUCT_NAME_SUM/monitor/plug/$sum-randr-args"; then
                        args=$(exec cat -- "$XDG_CONFIG_HOME/computer/$PRODUCT_NAME_SUM/monitor/plug/$sum-randr-args")
                    else
                        args=--auto
                    fi
                    eval command -- xrandr --output \
                        "$(exec cat -- "$XDG_CONFIG_HOME/computer/$PRODUCT_NAME_SUM/monitor/plug/$sum-port-randr")" \
                        "$args" && plug=$sum
                fi
            done

            if test -n "$native" && test -n "$plug"; then
                command -- xrandr --output \
                    "$(exec cat -- "$XDG_CONFIG_HOME/computer/$PRODUCT_NAME_SUM/monitor/$native-port-randr")" \
                    --off
            fi
        }

    if test "$X_XCLIENT" = bspwm; then
        command -- sh "$XDG_CONFIG_HOME/bspwm/bspwmrc"
    fi

    # if exec xrandr --listmonitors | command -- grep -F -q DP-4; then
    #     command -- xrandr --output DP-4 --primary --mode 1920x1080 --rotate normal
    # fi

    # if exec xrandr --listmonitors | command -- grep -F -q DP-5; then
    #     command -- xrandr --output DP-5 --mode 1920x1080 --rotate normal --right-of DP-4
    # fi

    command -- xset s 3600 60
    command -- xset dpms 0 0 0 -dpms
else
    test -t 1 && command -- fgconsole 1>/dev/null 2>&1 ||
        exit 1

    case $TERM in
        linux*)
            exec sudo setterm --blank 0 --powerdown 0 --powersave off
            ;;
    esac
fi

# vim: set ft=sh :
