#!/usr/bin/env bash
#
# Reconfigure audio devices.

# case $1 in
# 	(PCH)
# 		c=PCH;
# 		d=0;;
# 	(HDMI)
# 		c=HDMI;
# 		d=3;;
# 	(*)
# 		printf '?\n';
# 		exit 1;;
# esac;

# ed -s "$HOME/".asoundrc <<S
# /^c = /s/=.*$/= $c/
# /^d = /s/=.*$/= $d/
# w
# S

case ${PRODUCT_NAME_SUM:=$(exec -- get-product-name-as-sha256sum)} in
    859f65dacaab259e685498324e0c1e31f11fa50d26ddf907960448e9123eb2bd)
        case ${1,,} in
            pch | hdmi)
                exec -- ln -fsr -- "$HOME/.asoundrc_${1,,}" "$HOME/.asoundrc"
                ;;
        esac
        ;;
esac

# vim: set ft=zsh :
