#!/usr/bin/env bash
#
# Reconfigure network devices.
#
# Idea: https://github.com/vain/bin-pub/blob/master/cwm

if ((EUID)); then
    printf 'Must be run as root\n' 1>&2
    exit 1
fi

dhcplient_cf=/etc/dhcp/dhclient-d630.conf

e() {
    iface=${IFACE:-$(exec -- ip -br -4 addr | exec -- mawk '/^e/ { print $1; exit }')}
    iface=${iface:-enp5s0}

    case $1 in
        -c)
            command -- ip link set dev "$iface" up
            command -- sleep 1
            command -- dhclient -cf "$dhcplient_cf" "$iface"
            ;;
        -d)
            command -- dhclient -cf "$dhcplient_cf" -x "$iface"
            command -- ip link set dev "$iface" down
            ;;
        *)
            printf ?\\n 1>&2
            ;;
    esac
}

w() {
    iface=${IFACE:-$(exec -- ip -br -4 addr | exec -- mawk '/^w/ { print $1; exit }')}
    iface=${iface:-wlp3s0}

    case $1 in
        -wpa)
            : "${2:?}" "${3:?}"
            command -- ip link set dev "$iface" up
            command -- sleep 1
            command -- wpa_supplicant -B -i "$iface" -c <(exec -- wpa_passphrase "$2" "$3") &&
                command -- dhclient -cf "$dhcplient_cf" "$iface"
            ;;
        -c)
            command -- ip link set dev "$iface" up
            command -- sleep 1
            command -- wpa_supplicant -B \
                -c /etc/wpa_supplicant/wpa_supplicant.conf -i "$iface" &&
                command -- dhclient -cf "$dhcplient_cf" "$iface"
            ;;
        -s)
            command -- ip link set dev "$iface" up
            command -- sleep 1
            exec -- iw dev "$iface" scan |
                exec grep 'SSID\|freq\|signal\|capability' |
                command -- tac
            ;;
        -d)
            command -- dhclient -cf "$dhcplient_cf" -x "$iface" &&
                command -- wpa_cli -i "$iface" terminate
            command -- ip link set dev "$iface" down
            ;;
        *)
            printf ?\\n 1>&2
            ;;
    esac
}

case $1 in
    [ew])
        "$1" "${@:2}"
        ;;
    *)
        printf 'unknown arg\n' 1>&2
        exit 1
        ;;
esac

# vim: set ft=zsh :
