#!/usr/bin/env bash
#
# Reconfigure network devices.
#
# Idea: https://github.com/vain/bin-pub/blob/master/cwm

((UID)) && {
	printf 'Must be run as root\n' 1>&2;
	exit 1;
};

dhcplient_cf=/etc/dhcp/dhclient-d630.conf

e () {
	iface=${IFACE:-$(ip -br -4 addr | mawk '/^e/ { print $1; exit }')};
	iface=${iface:-enp5s0}

	case $1 in
		(-c)
			ip link set dev "$iface" up;
			sleep 1;
			dhclient -cf "$dhcplient_cf" "$iface";;
		(-d)
			dhclient -cf "$dhcplient_cf" -x "$iface";
			ip link set dev "$iface" down;;
		(*)
			printf ?\\n 1>&2;;
	esac;
};

w () {
	iface=${IFACE:-$(ip -br -4 addr | mawk '/^w/ { print $1; exit }')};
	iface=${iface:-wlp3s0};

	case $1 in
		(-wpa)
			: "${2:?}" "${3:?}";
			ip link set dev "$iface" up;
			sleep 1;
			wpa_supplicant -B -i "$iface" -c <(wpa_passphrase "$2" "$3") &&
				dhclient -cf "$dhcplient_cf" "$iface";;
		(-c)
			ip link set dev "$iface" up;
			sleep 1;
			wpa_supplicant -B \
					-c /etc/wpa_supplicant/wpa_supplicant.conf -i "$iface" &&
				dhclient -cf "$dhcplient_cf" "$iface";;
		(-s)
			ip link set dev "$iface" up;
			sleep 1;
			iw dev "$iface" scan |
			grep 'SSID\|freq\|signal\|capability' |
			tac;;
		(-d)
			dhclient -cf "$dhcplient_cf" -x "$iface" &&
				wpa_cli -i "$iface" terminate;
			ip link set dev "$iface" down;;
		(*)
			printf ?\\n 1>&2;;
	esac;
};

case $1 in
	([ew])
		"$1" "${@:2}";;
	(*)
		printf 'unknown device\n' 1>&2;
		exit 1;;
esac;

# vim: set ft=sh :
