#!/bin/sh
#
# Reconfigure camera.

: "${XDG_CONFIG_HOME:?}" "${PRODUCT_NAME_SUM:=$(exec get-product-name-by-md5sum)}"

command -- test-xorg ||
    exit 1

test -r "$XDG_CONFIG_HOME/computer/$PRODUCT_NAME_SUM/camera" &&
    exec xinput --disable "$(exec cat -- "$XDG_CONFIG_HOME/computer/$PRODUCT_NAME_SUM/camera")"

# vim: set ft=sh :
