#!/bin/sh
#
# Wrapper: Use taskwarrior in my 'reminder' context.

export TASKRC=${TASKRC:-$XDG_CONFIG_HOME/taskrc-life};

{
    task context reminder > /dev/null;
    task +reminder "$@";
    task context none > /dev/null;
} 2> /dev/null;

# vim: set ts=4 sw=4 tw=0 et :
