#!/bin/sh
#
# Wrapper: Rocket.Chat REST API.

server_address=${ROCKETCHAT_SERVER_ADDRESS:-https://rocketchat.wir.invalid};
auth_token=${ROCKETCHAT_REST_TOKEN:-$(command cat "$HOME/.rocketchat_wir_invalid_auth_token")};
user_id=${ROCKETCHAT_REST_USER_ID:-z6O73D6HJPjP9viLD};

readonly \
	server_address \
	auth_token \
	user_id;

curl() {
	url=$server_address$endpoint;

	# printf 'debug: method is %s\n' "$method" 1>&2;
	# printf 'debug: url is %s\n' "$url" 1>&2;

	exec curl -v -s \
		-H "X-User-Id: $user_id" \
		-H "X-Auth-Token: $auth_token" \
		-X "$(echo "$method" | command tr '[:lower:]' '[:upper:]')" \
		"$url" \
		${1:+"$@"};
}

get() {
	case ${1:?'error: endpoint missing'} in
		(channels.list|channels.list.joined|users.presence)
			endpoint=/api/v1/$1?count=999;;
		(*)
			endpoint=$1;;
	esac;

	\curl;
}

post() {
	endpoint=${1:?'error: endpoint missing'};
	data=$2;

	\curl -H 'Content-Type: application/json' ${data:+-d "$data"};
}

main() {
	local \
		data \
		endpoint \
		method \
		url;

	case $1 in
		(get|post)
			method=$1;;
		(*)
			echo 'error: valid method missing' 1>&2;
			return 1;
	esac;

	shift 1;

	"$method" "$@";
};

\main "$@";

# vim: set ft=sh :
