#!/usr/bin/env bash
#
# Libexec: Rocketchat REST API.

export API=${API:-${api:-rocketchat-rest-api}};

f_login() {
    local pw;
    read -e -s -r -p 'pw: ' pw;

    local \
        auth_token_file=$HOME/.rocketchat_auth_token \
        user=${1:-"error: user missing"};

    > "$auth_token_file";
    command chmod 640 "$auth_token_file";

    local auth_token=$(
        ROCKETCHAT_REST_TOKEN=. \
        ROCKETCHAT_REST_USER_ID=. \
        exec "$API" post login \
            '{"user": "'"$user"'", "password": "'"${pw:?error: pw missing}"'"}' |
        exec jq -r .data.authToken;
    );

    [[ -n "$auth_token" && "$auth_token" != null ]] || {
        echo 'login failed' 1>&2;
        exit 1;
    }

    printf '%s\n' "$auth_token" >> "$auth_token_file";
    printf '%s\n' "$auth_token";
}

f_logout() (
    local ROCKETCHAT_REST_USER_ID=${1:-"error: user id missing};

    local auth_token_file=$HOME/.rocketchat_auth_token;
    local ROCKETCHAT_REST_TOKEN=$(<"$auth_token_file") ||
        exit 1;

    export \
        ROCKETCHAT_REST_TOKEN \
        ROCKETCHAT_REST_USER_ID;

    exec "$API" post logout |
    exec jq -r .;

    exec rm "$auth_token_file";
)

${1:+"f_$@"};

# vim: set ft=sh :
