#!/usr/bin/env bash
#
# Run that command (X environment)
#
# -f fork into background
# -k keep/wait
# -n open cmd in new terminal-emulator

OPTIND=1
OPTERR=1
opt=

typeset -i \
        flag_f= \
        flag_k= \
        flag_n=;

typeset -a \
        command \
        command_quoted;

while
        getopts :fkn opt
do
        case $opt in
        f)
                flag_f=1
        ;;
        k)
                flag_k=1
        ;;
        n)
                flag_n=1
        ;;
        \?)
                printf "Unknown flag: '-%s'\n" "$OPTARG" 1>&2;
                exit 1
        esac
done
shift $(( OPTIND - 1 ))

typeset \
        a \
        q;

for a
do
        printf -v q '%q' "$a"
        command_quoted+=( "$q" )
        command+=( "$a" )
done


command -v "${command[0]}" 1>/dev/null 2>&1 || {
        printf "error: command not found: '%s'\n" "${command[0]}" 1>&2;
        exit 1
}

if
        test-tty 2>/dev/null;
then
        case ${flag_f}${flag_n}${flag_k} in
        111)
                daemonize x-terminal -e "${SHELL:-sh}" -c "${command[0]} ${command_quoted[@]:1};exec ${SHELL:-sh}"
        ;;
        110)
                daemonize x-terminal -e "${SHELL:-sh}" -c "${command[0]} ${command_quoted[@]:1}"
        ;;
        100)
                setsidw "${command[0]}" "${command[@]}"
        ;;
        011)
                x-terminal -e "${SHELL:-sh}" -c "${command[0]} ${command_quoted[@]:1};exec ${SHELL:-sh}"
        ;;
        010)
                x-terminal -e "${SHELL:-sh}" -c "${command[0]} ${command_quoted[@]:1}"
        ;;
        001)
                exec ${SHELL:-sh} -c "${command[0]} ${command_quoted[@]:1};builtin printf '%s\n' 'Press ENTER to continue';builtin read"
        ;;
        000)
                exec -a "${command[0]}" "${command[@]}"
        esac
else
        case ${flag_f}${flag_n}${flag_k} in
        111)
                daemonize x-terminal -e "${SHELL:-sh}" -c "${command[0]} ${command_quoted[@]:1};exec ${SHELL:-sh}"
        ;;
        110)
                daemonize x-terminal -e "${SHELL:-sh}" -c "${command[0]} ${command_quoted[@]:1}"
        ;;
        100)
                setsidw "${command[0]}" "${command[@]}"
        ;;
        011)
                daemonize x-terminal -e "${SHELL:-sh}" -c "${command[0]} ${command_quoted[@]:1};exec ${SHELL:-sh}"
        ;;
        010)
                daemonize x-terminal -e "${SHELL:-sh}" -c "${command[0]} ${command_quoted[@]:1}"
        ;;
        001)
                daemonize ${SHELL:-sh} -c "${command[0]} ${command_quoted[@]:1};builtin printf '%s\n' 'Press ENTER to continue';builtin read"
        ;;
        000)
                setsidw "${command[0]}" "${command[@]}"
        esac
fi

# vim: set ts=8 sw=8 tw=0 et :
