#!/bin/sh
#
# Run intellij-idea-ultimate.

command -- mkdir -p "/tmp/${USER:-$(exec id -un)}"

exec env \
    -u _JAVA_OPTIONS \
    _JAVA_AWT_WM_NONREPARENTING=1 \
    intellij-idea-ultimate "$@"

# vim: set ft=sh :
