#!/bin/sh
#
# Run chromium.

r=${XDG_CACHE_HOME:?}/run-chromium;

test -r "$r" -a -n "$force_new" && {
	t=$(mktemp -d);
	rsync -var --delete "$t/" "$r/";
	rm -rf -- "$t";
};

test -r "$r/"Default/Preferences || {
	mkdir -p -- "$r/"Default/Extensions;
	cat > "$r/"Default/Preferences <<!
{
  "AudioCaptureAllowed": false,
  "alternate_error_pages": {
    "enabled": false
  },
  "autofill": {
    "enabled": false
  },
  "bookmark_bar": {
    "show_apps_shortcut": false,
    "show_on_all_tabs": false
  },
  "browser": {
    "back_shortcut_bubble_shown_count": 1,
    "clear_data": {
      "form_data": true,
      "hosted_apps_data": true,
      "media_licenses": true,
      "passwords": true,
      "time_period": 4
    },
    "clear_lso_data_enabled": true,
    "custom_chrome_frame": false,
    "enable_spellchecking": false,
    "pepper_flash_settings_enabled": true,
    "show_home_button": true
  },
  "credentials_enable_service": false,
  "custom_handlers": {
    "enabled": false,
    "ignored_protocol_handlers": [],
    "registered_protocol_handlers": []
  },
  "default_search_provider_data": {
    "template_url_data": {
      "alternate_urls": [],
      "contextual_search_url": "",
      "created_by_policy": false,
      "date_created": "13130865345000000",
      "favicon_url": "https://duckduckgo.com/favicon.ico",
      "id": "2",
      "image_url": "",
      "image_url_post_params": "",
      "input_encodings": [
        "UTF-8"
      ],
      "instant_url": "",
      "instant_url_post_params": "",
      "keyword": "dd",
      "last_modified": "13130865345000000",
      "last_visited": "13137600727000000",
      "new_tab_url": "",
      "originating_url": "https://duckduckgo.com/opensearch.xml?atb=v50-6_b",
      "prepopulate_id": 0,
      "safe_for_autoreplace": false,
      "search_terms_replacement_key": "",
      "search_url_post_params": "",
      "short_name": "DuckDuckGo",
      "suggestions_url": "https://duckduckgo.com/ac/?q={searchTerms}&type=list",
      "suggestions_url_post_params": "",
      "url": "https://duckduckgo.com/?q={searchTerms}&atb=v50-6_b",
      "usage_count": 0
    }
  },
  "distribution": {
    "create_all_shortcuts": true,
    "import_bookmarks": false,
    "import_bookmarks_from_file": "/usr/share/chromium/initial_bookmarks.html",
    "make_chrome_default": false,
    "make_chrome_default_for_user": false,
    "show_welcome_page": false,
    "skip_first_run_ui": true,
    "suppress_first_run_default_browser_prompt": true
  },
  "download": {
    "directory_upgrade": true,
    "extensions_to_open": "",
    "open_pdf_in_system_reader": false,
    "prompt_for_download": true
  },
  "enable_do_not_track": true,
  "extensions": {
    "theme": {
      "id": "",
      "use_system": true
    },
    "toolbarsize": 2,
    "ui": {
      "developer_mode": true
    }
  },
  "homepage": "about:blank",
  "homepage_is_newtabpage": true,
  "http_original_content_length": "0",
  "http_received_content_length": "0",
  "local_discovery": {
    "notifications_enabled": false
  },
  "net": {
    "network_prediction_options": 2
  },
  "profile": {
    "password_manager_enabled": false
  },
  "pinned_tabs": [],
  "plugins": {
    "always_open_pdf_externally": false
  },
  "safebrowsing": {
    "enabled": false
  },
  "savefile": {
    "default_directory": "/home/files/tmp/downloads"
  },
  "search": {
    "suggest_enabled": false
  },
  "selectfile": {},
  "session": {
    "restore_on_startup": 4,
    "startup_urls": [
      "about:blank"
    ]
  },
  "spellcheck": {
    "dictionaries": [
      "en-US"
    ],
    "dictionary": ""
  },
  "toolbar_migrated_component_action_status": {},
  "translate": {
    "enabled": false
  },
  "webkit": {
    "webprefs": {
      "default_fixed_font_size": 12,
      "default_font_size": 15,
      "fonts": {
        "sansserif": {
          "Zyyy": "Sans"
        },
        "serif": {
          "Zyyy": "Serif"
        },
        "standard": {
          "Zyyy": "Serif"
        }
      },
      "minimum_font_size": 10,
      "minimum_logical_font_size": 10
    }
  },
  "zerosuggest": {
    "cachedresults": ""
  }
}
!
};

test -r "$r/Default/Web Data" ||
	sqlite3 -init /dev/stdin "$r/Default/Web Data" .quit <<\!
BEGIN TRANSACTION;
CREATE TABLE keywords (
  id INTEGER PRIMARY KEY,
  short_name VARCHAR NOT NULL,
  keyword VARCHAR NOT NULL,
  favicon_url VARCHAR NOT NULL,
  url VARCHAR NOT NULL,
  safe_for_autoreplace INTEGER,
  originating_url VARCHAR,
  date_created INTEGER DEFAULT 0,
  usage_count INTEGER DEFAULT 0,
  input_encodings VARCHAR,
  suggest_url VARCHAR,
  prepopulate_id INTEGER DEFAULT 0,
  created_by_policy INTEGER DEFAULT 0,
  last_modified INTEGER DEFAULT 0,
  sync_guid VARCHAR,
  alternate_urls VARCHAR,
  image_url VARCHAR,
  search_url_post_params VARCHAR,
  suggest_url_post_params VARCHAR,
  image_url_post_params VARCHAR,
  new_tab_url VARCHAR,
  last_visited INTEGER DEFAULT 0,
  created_from_play_api INTEGER DEFAULT 0
);
INSERT INTO `keywords` (id,short_name,keyword,favicon_url,url)
VALUES
 (2,'DuckDuckGo','dd','','https://duckduckgo.com/?q={searchTerms}&atb=v50-6_b'),
 (3,'debian => code','code','','http://codesearch.debian.net/search?q={searchTerms}'),
 (4,'duden','du','','http://www.duden.de/suchen/dudenonline/{searchTerms}'),
 (5,'google (DE)','gd','','https://www.google.de/search?q={searchTerms}&pws=0&gl=de&gws_rd=cr'),
 (6,'google (US)','ge','','https://www.google.com/search?q={searchTerms}&pws=0&gl=us&gws_rd=cr'),
 (7,'debian => man','man','','https://dyn.manpages.debian.org/jump?q={searchTerms}'),
 (8,'debian => packages','pack','','https://packages.debian.org/search?keywords={searchTerms}'),
 (9,'pons','po','','http://en.pons.com/translate?l=deen&q={searchTerms}'),
 (10,'wikipedia (DE)','wd','','https://de.wikipedia.org/w/index.php?title=Spezial:Suche&search={searchTerms}'),
 (11,'wikipedia (EN)','we','','https://en.wikipedia.org/w/index.php?title=Special:Search&search={searchTerms}'),
 (12,'youtube','yt','','https://www.youtube.com/results?search_query={searchTerms}');
COMMIT;
!

export CHROME_WRAPPER=$0;

exec chromium \
	--artifacts-dir=$r/artifacts \
	--crash-dumps-dir="$r/crash-dumps" \
	--disable-breakpad \
	--disable-cloud-import \
	--disable-component-cloud-policy \
	--disable-gpu-driver-bug-workarounds \
	--disable-infobars \
	--disable-payment-request \
	--disable-reading-from-canvas \
	--disable-speech-api \
	--disable-sync-preferences \
	--disable-translate \
	--disk-cache-dir=$r/cache \
	--enable-extension-activity-logging \
	--enable-fast-unload \
	--enable-gpu-rasterization \
	--enable-grouped-history \
	--enable-logging=stderr \
	--enable-potentially-annoying-security-features \
	--enable-reader-mode-toolbar-icon \
	--enable-site-settings \
	--enable-smooth-scrolling \
	--enable-spatial-navigation \
	--enable-strict-mixed-content-checking \
	--enable-strict-powerful-feature-restrictions \
	--enable-tab-audio-muting \
	--enable-webkit-text-subpixel-positioning \
	--enable-zero-copy \
	--error-console \
	--force-device-scale-factor="${GDK_SCALE:-1}" \
	--hide-scrollbars \
	--ignore-gpu-blocklist \
	--load-media-router-component-extension=0 \
	--log-net-log \
	--no-first-run \
	--no-wifi \
	--process-per-site \
	--user-data-dir=$r \
	${1:+"$@"};

# vim: set ft=sh :
