#!/bin/sh
#
# Run logger.
#
# For local scripting.
# Needs facility local6 to work properly with my configured rsyslog.
#
# $ run-logger level category [summary [body]]

l=$1
c=$2

shift 2

exec logger -d -s --id="$PPID" \
    -t "$(exec basename "$(exec strings "/proc/$PPID/cmdline")")" \
    -p "local6.$l" "$c" "$@"

# vim: set ft=sh :
