#!/usr/bin/env bash
#
# Run rtcwake in mem mode and play music/radio on wakeup.

function bye {
    printf 'Bye-bye!\n' 1>&2
    exit "${1:-0}"
}

if command -- test-xorg; then
    function __menu {
        command -- menu dmenu2 "$1"
    }
elif command -- test-ctty; then
    function __menu {
        command -- menu fzf "$1"
    }
else
    bye 1
fi

declare -A music=(
    [radio1]=http://www.radioeins.de/live.m3u
    [open]=${XDG_MUSIC_DIR:?}/open_your_eyes.mp3
)

days=(
    "$(exec -- date --date=now +%F)"
    "$(exec -- date --date=tomorrow +%F)"
)

date_time=$(
    for d in "${days[@]}"; do
        printf '%s\n' "$d "{00..23}:{00..59}
    done |
        __menu "Date (now: $(date +%R))"
)
[[ -n $date_time ]] || bye

key=$(printf "%s\n" "${!music[@]}" | __menu Play)
[[ -n $key ]] || bye

go=$(printf %s\\n exit "rtcwake $date_time $key" | __menu Run)

if [[ -n $go && $go != exit ]]; then
    command -- sudo rtcwake --mode mem --time "$(exec -- date -d "$date_time" +%s)" ||
        exit 1
    command -- sleep 10 && exec -- audio-player --loop=inf "${music[$key]}"
else
    bye
fi

# vim: set ft=zsh :
