#!/bin/sh
#
# Run source-highlight.

trap 'exec tput sgr0' EXIT

for f; do
    command -- source-highlight \
        --failsafe \
        --infer-lang \
        -f esc-solarized \
        --outlang-def="${XDG_DATA_HOME:?}/source-highlight/solarized/esc-solarized.outlang" \
        --style-file="$XDG_DATA_HOME/source-highlight/solarized/esc-solarized.style" \
        -o STDOUT \
        --tab=4 \
        --line-number=0 \
        -i "$f"
    echo
done

# vim: set ft=sh :
