#!/bin/sh
#
# Run feedfaetcher.

feedcacherdir=${XDG_VAR_HOME:?}/lib/feedfaetcher
urllist=$feedcacherdir/urls.txt

command -- mkdir -p -- "$feedcacherdir"

if test -n "$1"; then
    list=$(exec cat -- "$urllist" - | exec sort -u) <<-IN
		$1
	IN
    echo "$list" >"$urllist"
else
    exec feedfaetcher
fi

# vim: set ft=sh noexpandtab :
