#!/bin/sh
#
# Run weekly borg backup.

hostname=$(exec uname -n | exec tr '[:lower:]' '[:upper:]')

exec sudo \
    HOME=${HOME:?} \
    XDG_CACHE_HOME=${XDG_CACHE_HOME:?} \
    BORG_REPO=/media/user1/a5a5b889-14f5-475d-86fc-b67bcd8f247a/linux/$hostname/borg/ \
    BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK=yes \
    sh -c '
        exec 1>&2

        echo CREATING ...
        command -- borg create --warning --progress --stats \
            --exclude-caches \
            --exclude-nodump \
            --exclude-from /dev/stdin \
            --comment auto \
            --compression none \
            ::{now:%Y-%m-%dT%H:%M:%S.%f} \
            /etc/ \
            /home/ \
            /root/ \
            /usr/local/ \
            /usr/share/chromium/ \
            /var/backups/ \
            /var/mail/ \
            /var/sieve/ \
            /var/vmail/ \
            /var/www/ <<-EXCLUDE || exit
				/home/latch/tmp
				/home/latch/var/mirror
				$XDG_CACHE_HOME
				$HOME/opt
				$HOME/.vifm/Trash
			EXCLUDE

        echo PRUNING ...
        exec borg prune --warning --progress --stats --list --keep-within=12w ::
    '

# vim: set ft=sh noexpandtab :
