#!/bin/sh
#
# Run pwgen.

until test "${#p}" -ge 256; do
    p=$(
        exec pwgen -cnsyC -N 64 -r \'\"\`\$\\ |
            exec tr -dc "${1:-[:graph:]}"
    )
done

printf '%s' "$p" |
    exec cut -b "1-${2:-64}"

# vim: set ft=sh :
