#!/bin/sh
#
# Run generate-bookmarks-file.
# Generates bookmarks.md and converts it into bookmarks.html.

repo=$HOME/src/bookmarks

cd -- "$repo" ||
    exit 1

export \
    GIT_DIR \
    GIT_WORK_TREE
GIT_WORK_TREE=$repo
GIT_DIR=$repo/.git

command -- generate-bookmarks-file &&
    command -- pandoc bookmarks.md -f markdown -s -o bookmarks.html &&
    command -- git add bookmarks.md bookmarks.html &&
    command -- git commit -m "$(exec fortune -as -n 80)" &&
    exec git push -u --tags origin master
