#!/bin/sh
#
# My suspend wrapper.

# sudo rtcwake -m mem -t "$(date -d year +%s)";
sudo systemctl suspend;

sleep 5;

test -n "$X_XCLIENT" &&
	. "$HOME/".profile.d/run.sh &&
		ProfileRcRunXCustoms;

# vim: set ft=sh :
