#!/bin/sh
#
# Take a quick multi screenshot.

mkdir -p /tmp/screenshots;

exec scrot \
    '%Y-%m-%d--%s_$wx$h.png' \
    -q 100 \
    -m \
    -e 'mv $f /tmp/screenshots';

# vim: set ts=4 sw=4 tw=0 et :
