#!/bin/sh
#
# Control spotify via mpris player interface.

case ${1:?} in
(Next|Previous|Pause|PlayPause|Stop)
	;;
(*)
	printf 'errror: unknown method\n' 1>&2;
	exit 1;
esac;

exec dbus-send \
 --print-reply \
 --dest=org.mpris.MediaPlayer2.spotify \
 /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player".$1";

# vim: set ft=sh :
