#!/usr/bin/env bash
#
# Stat a file and build an associative array.

if
    [[ $1 == -f ]];
then
    shift 1;
    { stat --file-system --printf="$(</dev/fd/0)\n" "$1"; } <<'SEQ'
STAT[a|%n]=%a
STAT[b|%n]=%b
STAT[c|%n]=%c
STAT[d|%n]=%d
STAT[f|%n]=%f
STAT[i|%n]=%i
STAT[l|%n]=%l
STAT[s|%n]=%s
STAT[S|%n]=%S
STAT[t|%n]=%t
STAT[T|%n]=%T
SEQ
else
    { stat --printf="$(</dev/fd/0)\n" "$1"; } <<'SEQ'
STAT[a|%n]=%a
STAT[A|%n]=%A
STAT[b|%n]=%b
STAT[B|%n]=%B
STAT[d|%n]=%d
STAT[D|%n]=%D
STAT[f|%n]=%f
STAT[F|%n]='%F'
STAT[g|%n]=%g
STAT[G|%n]='%G'
STAT[h|%n]=%h
STAT[i|%n]=%i
STAT[m|%n]='%m'
STAT[o|%n]=%o
STAT[s|%n]=%s
STAT[t|%n]=%t
STAT[T|%n]=%T
STAT[u|%n]=%u
STAT[U|%n]='%U'
STAT[w|%n]=%w
STAT[W|%n]=%W
STAT[X|%n]=%X
STAT[Y|%n]=%Y
STAT[Z|%n]=%Z
SEQ
fi;

# vim: set ft=sh :
