#!/bin/sh
#
# Use st like kuake and yeahconsole terminal.
# Idea: https://wiki.archlinux.org/index.php/ \
#       Urxvt#Improved_Kuake-like_behavior_in_Openbox

dz () {
    test -e "$XDG_RUNTIME_DIR/"DAYLIGHT &&
        shift 1;

    daemonize "$1" -i -c stj1 -t stj1 -g 176x33+1+0 -e "$SHELL" -c '
        printf "%x\n" "$WINDOWID" > "${XDG_RUNTIME_DIR:?}/stj1";
        exec "$0";';

    exit 0;
};

read -r id < "${XDG_RUNTIME_DIR:?}/"stj1 2>/dev/null;

xprop -id "0x$id" 1>/dev/null 2>&1 ||
    dz st-dark st-light;

if
    xprop -root -notype -f _NET_CLIENT_LIST 32x \$0+, _NET_CLIENT_LIST |
    grep -F -q "0x$id,";
then
    xdotool windowunmap "0x$id";
else
    #xdotool mousemove --sync 0 0
    xdotool windowmap --sync "0x$id";
    #wmctrl -i -a "0x${id}"
    #xdotool windowraise "0x${id}"
    #xdotool windowfocus --sync "0x${id}"
    #xdotool mousemove --sync 0 0
fi;

# vim: set ts=4 sw=4 tw=0 et :
