#!/usr/bin/env bash
#
# Stream music links from my gist file.

while
	read -r;
do
	audio-player "$REPLY";
	read -r < /dev/tty;
	[[ $REPLY == q ]] && exit;
done < <(
	curl https://gist.githubusercontent.com/d630/323420bbb1466bcd58925df610ed5fcd/raw/053e161f9e8ea3102be6b3a5388bdc3e6cc701ba/spotify.md |
	sed -n 's/^.*(\([^ ]*\))$/\1/p'
)

# vim: set ft=sh :
