#!/bin/sh
#
# Display most swap-using processes.
#
# Source: http://chneukirchen.org/dotfiles/bin/swaptop

if command -- grep -q -F VmSwap /proc/1/status; then
    exec mawk '
        /^Name:/ {
            name = $2
        };
        /^Pid:/ {
            pid = $2
        };
        /^VmSwap:/ {
            swap = $2
            if (swap > 0) {
                printf "%8d  %s %d\n", swap, name, pid
            }
        }
    ' /proc/[0-9]*/status |
        exec sort -r
else
    for f in /proc/[0-9]*; do
        command -- mawk '
            BEGIN {
                swap = 0
            };
            $30 {
                pid = $1;
                name = substr($2, 2, length($2) - 2)
            };
            $1 == "Swap:" {
                swap += $2
            };
            END {
                if (swap > 0) {
                    printf "%8d  %s %d\n", swap, name, pid
                }
            }
        ' "$f/stat" "$f/smaps" 2>/dev/null
    done |
        exec sort -r
fi

# vim: set ft=sh :
