#!/bin/sh
#
# Restart sxhkd.

p=${XDG_RUNTIME_DIR:?}/sxhkd.pid;

if
    test -r "$p";
then
    pkill -F "$p";
else
    pkill -f sxhkd\ -c;
fi;

(
    exec sxhkd -c "$XDG_CONFIG_HOME/"sxhkd/sxhkdrc &
    echo $! > "$p";
);

# vim: set ft=sh :
