#!/usr/bin/env bash
#
# Open all files in the current directory with sxiv.
# source: archlinux wiki

shopt -s nullglob;

[[ -f $1 ]] || {
    printf '%s: first argument is not a file' "$0" 1>&2;
    exit 1;
};

typeset \
    file=$(basename -- "$1") \
    dir=$(dirname -- "$1");
typeset -a arr=();

shift 1;

cd -- "$dir" ||
 exit 1;

for i in *; do
    [[ -f $i ]] ||
        continue;
    arr+=("$i")
    [[ $i == "$file" ]] &&
        c=$((${#arr[@]} - 1));
done;

setsidw sxiv "$@" -- "${arr[@]:c}" "${arr[@]:0:c}";

# vim: set ft=sh :
