#!/bin/sh
#
# Run task colors: Display color info in terminal.

printf 'TERM: %s\nCOLORS: %d\nLONGNAME: %s\n' \
    "$TERM" \
    "$(exec tput colors)" \
    "$(exec tput longname)"

exec task rc._forcecolor=on colors
# weechat -c;

# vim: set ft=sh :
