#!/bin/sh
#
# Simple wrapper for using taskwarrior with local "task-repos".

export TASKRC=${TASKRC:-$PWD/.task/taskrc}

case $1 in
    init)
        if test -d "$PWD/.task"; then
            printf '%s:Error:82: Could not create a task repository: "%s/.task/" already exists\n' \
                "$0" "$PWD" 1>&2
            exit 82
        else
            command -- mkdir -p -- "$PWD/.task/data" &&
                exec task config data.location "$PWD/.task/data"
        fi
        ;;
    --)
        shift 1
        exec task "$@"
        ;;
    *)
        printf '%s:Error:83: Unknown parameter: %s\n' "$0" "$1" 1>&2
        exit 83
        ;;
esac

# vim: set ft=sh :
