#!/usr/bin/env bash
#
# Add interactively a task to Taskwarrior via read in a terminal + {d,s}menu.

if
    test-tty 2>/dev/null;
then
    function __menu_cmd {
        menu slmenu "$1";
    };
elif
    [[ -n $DISPLAY ]];
then
    function __menu_cmd {
        menu dmenu2 "$1";
    };
else
    exit 1;
fi;

printf 'Choose a project, insert a new one or escape ...\n' 1>&2;
project=$(
    {
        printf 'NEW\n';
        task rc.list.all.projects=yes _unique project |
        sed '
            /^log\./ {
                d;
                b end;
            }; {
                p;
                s/^\([^\.]*\)\..*/\1/;
            };
            : end' |
        sort -gu;
    } |
    __menu_cmd PROJECT;
);

[[ $project == NEW ]] && project=$(
    __menu_cmd PROJECT <<<'';
);

printf 'project:        %s\n' "$project";

read -re -p 'description:    ' description;

while
    :;
do
    tag=$(
        {
            printf 'NEW\n';
            task rc.list.all.tags=yes _unique tags |
            tr , \\n |
            sort -gu;
        } |
        __menu_cmd TAG;
    );
    [[ $tag == NEW ]] && tag=$(
        __menu_cmd TAG <<<'';
    );
    if
        [[ -n $tag ]];
    then
        printf '+%s\n' "$tag";
        tags+=("$tag");
    else
        break;
    fi;
done;

read -re -p 'priority:       ' priority;
read -re -p 'due:            ' due;
read -re -p 'recur:          ' recur;
read -re -p 'wait:           ' wait;
read -re -p 'until:          ' until;
read -re -p 'scheduled:      ' scheduled;
read -re -p 'depends:        ' depends;
read -re -p 'entry:          ' entry;

printf '\nCommand:       task add %s project:%s due:%s priority:%s recur:%s wait:%s until:%s scheduled:%s depends:%s entry:%s %s\n' "$description" "$project" "$due" "$priority" "$recur" "$wait" "$until" "$scheduled" "$depends" "$entry" "${tags[*]/#/+}";

task add "$description" ${project:+"project:$project"} ${due:+"due:$due"} ${priority:+"priority:$priority"} ${recur:+"recur:$recur"} ${wait:+"wait:$wait"} ${until:+"until:$until"} ${scheduled:+"scheduled:$scheduled"} ${depends:+"depends:$depends"} ${entry:+"entry:$entry"} ${tags[*]/#/+};

# vim: set ts=4 sw=4 tw=0 et :
