#!/usr/bin/env bash
#
# Test if tty is available.

[[ $BASH_SOURCE == $0 ]] || {
    printf 'Error: Do not execute me via source\n' 1>&2;
    return 1 2>/dev/null;
};

tty=$(ps -p $PPID -o tty=);
tty=${tty/\?/};

[[ -n $tty ]] &&
    printf /dev/%s\\n "$tty" 1>&2;

# vim: set ft=sh :
