#!/usr/bin/env bash
#
# Print battery capacity.

shopt -s nullglob;

b=(/sys/class/power_supply/CMB*);
[[ ${#b} -ne 0 && $(< $b/status) == Discharging ]] &&
	echo $(< $b/capacity);

# vim: set ts=2 sw=2 tw=0 noet :
