#!/usr/bin/env bash
#
# Adjust theme configuration.

theme.bspwm ()
{
        bspc config active_border_color "$1"
        bspc config focused_border_color "$1"
        bspc config normal_border_color "$2"
        bspc config presel_feedback_color "$1"
}

theme.gtk ()
(
        cd -- "$HOME"
        ln -fsr ".gtkrc-2.0-${1}.mine" \
                ".gtkrc-2.0-theme.mine";
        ln -fsr "etc/gtk-3.0/settings-${1}.ini" \
                "etc/gtk-3.0/settings.ini";
)

theme.mutt ()
(
        cd -- "${XDG_DATA_HOME}/mutt/colors"
        ln -fsr "$1" "${HOME}/.mutt/mutt-colors.muttrc"
)

theme.taskwarrior ()
(
        cd -- "$HOME"
        ln -fsr "/usr/share/taskwarrior/${1}" "${HOME}/.taskrc-color"
)

theme.x ()
(
        cd -- "${XDG_DATA_HOME}/xcolors"
        ln -fsr "$1" "current.xcolor"
        xrdb -merge "${HOME}/.Xresources"

        xsetroot -solid "$2"

        cd -- "${XDG_DATA_HOME}/wallpapers"
        ln -fsr "${3}" "current.wallpaper";
        feh --bg-fill "${XDG_DATA_HOME}/wallpapers/current.wallpaper"
)

declare -A C

if
        [[ $1 == dark ]]
then
        rm -f "${XDG_CACHE_HOME}/DAYLIGHT"
        C=(
                [gtk.1]=dark
                [taskwarrior.linux.1]=dark-16.theme
                [taskwarrior.256.1]=solarized-dark-256.theme
                [mutt.linux.1]=mutt-colors-solarized-light-16.muttrc
                [mutt.256.1]=mutt-colors-solarized-light-256.muttrc
                [x.1]=Solarized-Dark.xcolor
                [x.2]=\#002B36
                [x.3]=debian-minimal-dark.png
                [bspwm.1]=\#555555
                [bspwm.2]=\#222222
        )
else
        > "${XDG_CACHE_HOME}/DAYLIGHT"
        C=(
                [gtk.1]=light
                [taskwarrior.linux.1]=light-16.theme
                [taskwarrior.256.1]=solarized-light-256.theme
                [mutt.linux.1]=mutt-colors-solarized-light-16.muttrc
                [mutt.256.1]=mutt-colors-solarized-light-256.muttrc
                [x.1]=Solarized-Light.xcolor
                [x.2]=\#FDF6E3
                [x.3]=debian-minimal-light.png
                [bspwm.1]=\#555555
                [bspwm.2]=\#E0E0E0
        )
fi

if
        [[ $TERM == linux* ]]
then
        theme.taskwarrior "${C[taskwarrior.linux.1]}"
        theme.mutt "${C[mutt.linux.1]}"
else
        theme.taskwarrior "${C[taskwarrior.256.1]}"
        theme.mutt "${C[mutt.256.1]}"
fi

if
        [[ -n $DISPLAY ]]
then
        theme.x "${C[x.1]}" "${C[x.2]}" "${C[x.3]}"
        theme.gtk "${C[gtk.1]}"
        case $X_XCLIENT in
        bspwm)
                theme.bspwm "${C[bspwm.1]}" "${C[bspwm.2]}"
        esac
fi

exit 0

# vim: set ts=8 sw=8 tw=0 et :
