#!/usr/bin/env bash
#
# Update via some package managers.

cd -- "$XDG_OPT_HOME" ||
	exit 1;

printf -v horiz %\*s 80 '';
function PrintHeader {
    printf %s\\n "${horiz// /-}" "$1" 1>&2;
};

PrintHeader 'Apt && Packages';
sudo sh -c '
	dpkg --configure -a;
	apt-get install -f;
	apt-get autoremove --purge;
	dpkg --clear-avail;
	apt-get autoclean;
';

PrintHeader cpan\ modules;
cpan-outdated -p --exclude-core |
cpanm -iv --self-contained;

PrintHeader latch;
/home/latch/bin/latch mr mirror;

PrintHeader npm\ modules;
npm update -g;

PrintHeader go\ packages;
go get -v -u "$GOPATH/...";

PrintHeader cabal\ packages;
cabal v1-update;
cabal v1-install world --upgrade-dependencies --force-reinstalls;

PrintHeader composer\ packages;
composer global update;

PrintHeader python3;
pip3 freeze --user |
sed 's:==.*::' |
xargs pip3 install --user --upgrade;

# vim: set ft=sh :
