#!/bin/sh
#
# Update all mirrored wir git repositories.

src=${1:-$HOME/src/wir}

exec find -H "$src" \
    -mindepth 2 \
    -maxdepth 2 \
    -type d \
    -print0 |
    exec xargs -0 -n 1 -P 0 -- sh -c '
        test -d "$1/.git" ||
            exit 1

        export \
            GIT_DIR \
            GIT_WORK_TREE
        GIT_WORK_TREE=$1
        GIT_DIR=$1/.git

        eval "$(exec git config --local --get --bool core.bare)" &&
            exec git remote update --prune
    ' --

# vim: set ft=sh :
