#!/bin/sh
#
# Set volume via amixer.

case $1 in
    (\+)
        amixer -q sset Master 2+;;
    (\+\+)
        amixer -q sset Master 2%+;;
    (-)
        amixer -q sset Master 2-;;
    (--)
        amixer -q sset Master 2%-;;
    (toggle)
        amixer -q sset Master toggle;;
esac;

# vim: set ft=sh :
