#!/bin/sh
#
# (Un-)Watch all wir git repositories.

# post|delete
method=${1:-post};

get-all-wir-repo-slugs 2>/dev/null |
jq -r '
	.[] |
	"/rest/api/latest/projects/\(.project_key)/repos/\(.repo_slug)/watch"
' |
xargs -L 1 -n 1 -P 0 bitbucket-rest-api "$method" 2>/dev/null;

# vim: set ft=sh :
