#!/bin/sh
#
# (Un-)Watch all confluece spaces.

username=d630
# delete|post
method=${1:-post};

get-all-confluence-space-keys 2>/dev/null |
grep -F -v -e "~$username" -e DEV |
xargs -L 1 -n 1 -P 0 -I {} confluence-rest-api "$method" \
	"/rest/api/user/watch/space/{}?username=$username" \
	1>/dev/null 2>&1;

# vim: set ft=sh :
