#!/usr/bin/env bash
#
# Simple wradio.
# Forked from webradio.sh (GNU GPLv3) by Markus Lux, 2013
# https://github.com/mlux/webradio.sh/blob/master/webradio.sh

if
    test-ctty;
then
    function __menu {
        menu fzf PLAY;
    };
elif
    [[ -n $DISPLAY ]];
then
    function __menu {
        menu dmenu2 PLAY;
    };
else
    exit 1;
fi;

file_webradio_streams=${XDG_VAR_HOME:?}/lib/wradio/streams;
file_webradio_pid=${XDG_VAR_HOME:?}/lib/wradio/instance.pid;

function __build_streams {
    typeset \
        name \
        uri;

    while
        IFS=\; read -r name uri;
    do
        streams[$name]=$uri;
    done < "$file_webradio_streams";
};

function __selectstream {
    selection=$(
        printf %s\\n STOPSTREAM "${!streams[@]}" |
        sort -u |
        __menu;
    );
};

function __stopstream
if
    [[ -r $file_webradio_pid ]];
then
    pkill -9 -F "$file_webradio_pid" 1>/dev/null 2>&1;
    rm -f -- "$file_webradio_pid" 1>/dev/null 2>&1;
fi;

function __playstream () (
    exec audio-player --no-terminal "${streams[$selection]}" 1>/dev/null 2>&1 &
    echo "$!" >> "$file_webradio_pid";
);


typeset -A streams;
__build_streams;

while
    :;
do
    __selectstream;
    case $selection in
        (STOPSTREAM)
            __stopstream;;
        ('')
            exit 1;;
        (*)
        __stopstream;
        __playstream;;
    esac;
done;

# vim: set ft=sh :
