#!/bin/sh
#
# Default terminal emulator window.

IFS=\|;
set -f;

if
    test -f "${XDG_RUNTIME_DIR:?}/DAYLIGHT";
then
    set -- $TERMINAL_L_OPTS ${1:+"$@"};
    exec "$TERMINAL_L" "$@";
else
    set -- $TERMINAL_D_OPTS ${1:+"$@"};
    exec "$TERMINAL_D" "$@";
fi;

# vim: set ft=sh :
