#!/bin/sh
#
# Open some terminal emulators in tabbed.

xid=$(exec tabbed -cd -n terminal-tabbed 2>/dev/null)
: "${xid:?}"

case $X_XCLIENT in
    x-terminal-tabbed)
        command -- xdotool windowsize "$xid" 100% 100%
        ;;
esac

{
    command -- urxvt -embed "$xid" &
    command -- xterm -into "$xid" &
    command -- sleep 0.5
    command -- x-terminal -w "$xid" &
} 2>/dev/null

wait

# vim: set ft=sh :
