#!/usr/bin/env dash
#
# Switch keyboard layout and take the necessary actions.
# and do not use 'setxkbmap -option grp:alt_shift_toggle'.

if
        xkblayout-state set +1
then
        layout="$(xkblayout-state print "%s-%e")"
        case "$X_XCLIENT" in
        # openbox)
        #         for i in "${XDG_CONFIG_HOME}/openbox/${layout}"/*
        #         do
        #                 ln -vsrf "$i" -t "${XDG_CONFIG_HOME}/openbox"
        #         done
        #         xdotool key Super_L+q && sleep 1 && xdotool key Super_L+b
        #         ln -vsrf "${XDG_CONFIG_HOME}/xbindkeys/${layout}/xbindkeysrc_ob" \
        #                 "${XDG_CONFIG_HOME}/xbindkeys/xbindkeysrc";
        #         return 0
        # ;;
        bspwm|cwm|spectrwm|fallback)
                :
        ;;
        *)
                X_XCLIENT=fallback
        esac
        ln -vsrf "${XDG_CONFIG_HOME}/sxhkd/${layout}/sxhkdrc_${X_XCLIENT}" \
                "${XDG_CONFIG_HOME}/sxhkd/sxhkdrc";
fi

# vim: set ts=8 sw=8 tw=0 et :
