#!/bin/sh
#
# Select X desktop with a menu and then switch with wmctrl to it.

desk=$(exec wmctrl -d | exec menu dmenu2 \>)

if test -n "$desk"; then
    exec wmctrl -s "${desk%% *}"
fi

# vim: set ft=sh :
