#!/usr/bin/env dash
#
# Select desktop with a menu and then switch with wmctrl to it.

desk="$(
        wmctrl -d \
        | menu "dmenu2" ">";
)"
wmctrl -s "${desk%% *}"

# vim: set ts=8 sw=8 tw=0 et :
