#!/bin/sh
#
# Default xlock programme.

t ()
{
        xset -dpms
}

trap t INT TERM QUIT EXIT HUP
xset dpms 3 3 3
i3lock \
        --nofork \
        --image=${XDG_DATA_HOME}/wallpapers/current.wallpaper \
        --no-unlock-indicator \
        --show-failed-attempts \
        --tiling;

# vim: set ts=8 sw=8 tw=0 et :
