#!/bin/sh
#
# Grab xwindow and get xclass info.

exec xprop |
    exec mawk '
        /^WM_CLASS/ {
            sub(/.* =/, "instance:");
            sub(/,/, "\nclass:");
            print
        }

        /^WM_NAME/ {
            sub(/.* =/, "title:")
            print
        }
    '

# vim: set ft=sh :
