#!/bin/sh
#
# Print the X primary selection to stdout.

command -- xsel -l /dev/null -k
command -- xsel -l /dev/null --primary --output
# xclip -quiet -loops 0 -selection primary -out;

# vim: set ft=sh :
