#!/bin/sh
#
# Default X screen autolocker program.

exec daemonize xss-lock \
    -n "run-logger 3 .misc.exlamation 'Screen is going to be locked'" \
    -- "${XDG_BIN_HOME:?}/xorg-locker"

# vim: set ft=sh :
