#!/bin/sh
#
# Read into X clipboard selection.

# xclip -selection clipboard -in -loops 0;

{
    tee /dev/fd/9 |
    xorg-selection-primary-in
} 9>&1 |
exec xsel -l /dev/null --clipboard --input &

# vim: set ts=4 sw=4 tw=0 et :
