#!/bin/sh
#
# List xwindows with dmenu and raise selection.

#wmctrl -i -a "$(wmctrl -lGpx | column -t | menu.sh "dmenu2" ">" | awk '{print $1}')"

id=$(
    wmctrl -lGpx |
    column -t |
    menu dmenu2 \> |
    mawk '{ print $1 }';
);

test -n "$id" && {
    #xdotool windowmap $id
    #wmctrl -i -r $id -b remove,hidden
    #xdotool windowraise $id
    #xdotool windowfocus $id
    #xdotool mousemove --window $id 25 25
    #xdotool click 1
    wmctrl -i -a "$id";
};

# vim: set ts=4 sw=4 tw=0 et :
