#!/bin/sh
#
# Select desktop with a menu and then switch with wmctrl to it.

desk=$(
    wmctrl -d |
    menu dmenu2 \>;
);

test -n "$desk" &&
    wmctrl -s "${desk%% *}";

# vim: set ts=4 sw=4 tw=0 et :
