#!/usr/bin/env bash
#
# Read into X clipboard selection.

# xclip -selection clipboard -in -loops 0;

tee >(xsel -l /dev/null --clipboard --input) |
xorg-selection-primary-in;

# {
#     tee /dev/fd/9 |
#     xorg-selection-primary-in;
# } 9>&1 |
# exec xsel -l /dev/null --clipboard --input &

# vim: set ft=sh :
