#!/bin/sh
#
# Run youtoube-dl to convert video to audio.

#set -e

IFS=;

while
	read -r i;
do
	youtube-dl \
		--external-downloader=aria2c \
		--output='%(title)s.%(ext)s' \
		--restrict-filenames \
		--continue \
		--no-overwrites \
		--no-cache-dir \
		--print-traffic \
		--no-call-home \
		--prefer-free-formats \
		--extract-audio \
		--audio-format=${1:-vorbis} \
		--prefer-ffmpeg \
		"$i";
done;

# vim: set ft=sh :
