#!/bin/sh
#
# Run youtoube-dl to convert video to audio.

#set -e

while read -r i; do
    youtube-dl \
        --external-downloader=aria2c \
        --output='%(title)s.%(ext)s' \
        --restrict-filenames \
        --continue \
        --no-overwrites \
        --no-cache-dir \
        --print-traffic \
        --no-call-home \
        --prefer-free-formats \
        --extract-audio \
        --audio-format=vorbis \
        --prefer-ffmpeg \
        "$i";
done;

# vim: set ts=4 sw=4 tw=0 et :
