#!/bin/sh
#
# Run z output within file manager.

if
    test-tty 2>/dev/null;
then
    menu=fzf;
    __nav () {
        exec file-browser "$1";
    };
elif
    test -n "$DISPLAY";
then
    menu=dmenu2;
    __nav () {
        setsidw x-file-browser -t "$1";
    };
else
    exit 1;
fi;

path=$(
    sort -g "$XDG_VAR_HOME/"lib/z/z.data |
    cut -d \| -f 1 |
    menu "$menu" OPEN;
);

test -d "$path" &&
    __nav "$path";

# vim: set ft=sh :
