#!/bin/sh
#
# Display all zombies and their parents to kill.
# Source: http://chneukirchen.org/dotfiles/bin/zombies

ps f -eo state,pid,ppid,comm |
mawk '
    { cmds[$2] = $NF }
    /^Z/ {
        print $(NF-1) "/" $2 " zombie child of " cmds[$3] "/" $3;
    }';

# vim: set ft=sh :
