#!/bin/sh
#
# Take a quick camera snapshot.

mkdir -p /tmp/camera-snapshots;

exec ffmpeg \
    -f video4linux2 \
    -s 640x480 \
    -i /dev/video0 \
    -ss 0:0:2 \
    -frames 1 \
    "/tmp/camshots/$(date +%s).jpg";

# vim: set ft=sh :
