#!/usr/bin/env bash
#
# Search google.
# Source: http://chneukirchen.org/dotfiles/bin/goog

Q=$*

printf '%s\n' "$(
        curl -A Mozilla/4.0 -skLm 10 \
                "http://www.google.com/search?nfpr=\&q=${Q// /+}" \
        | grep -oP '\/url\?q=.+?&amp' \
        | sed 's/\/url?q=//;s/&amp//;s/\%/\\x/g';
)"

# vim: set ts=8 sw=8 tw=0 et :
