#!/bin/sh
#
# Wrapper: imapfilter with config localhost-delete.lua.
# TODO

exec imapfilter \
    -c "$HOME/".imapfilter/localhost-delete.lua \
    -l "${XDG_VAR_HOME:?}/"log/imapfilter.log

# vim: set ft=sh :
