#!/bin/sh
#
# Weekly backup with obnam.

exec sudo \
    HOME=$HOME \
    XDG_CACHE_HOME=$XDG_CACHE_HOME \
    obnam_conf=$HOME/.obnam.conf \
    sh -c '
    obnam backup --config"=$obnam_conf" --lru-size=8192 --upload-queue-size=8192 \
        --exclude=/home/latch/tmp \
        --exclude=/home/latch/var/mirror \
        --exclude=$XDG_CACHE_HOME \
        /etc/ \
        /home/ \
        /root/ \
        /var/backups/ \
        /var/lib/bitlbee \
        /var/mail/ \
        /var/sieve/ \
        /var/vmail/ \
        /var/www/;

    obnam force-lock --config"=$obnam_conf";

    obnam forget --config"=$obnam_conf" --keep=2w;
'

# vim: set ft=sh :
