#!/usr/bin/env bash
#
# Stream music links from my gist file.

while
	read -r;
do
	audio-player "$REPLY";
	read -r -t 3 < /dev/tty;
	[[ $REPLY == q ]] && exit;
done < <(
	curl https://gist.githubusercontent.com/d630/323420bbb1466bcd58925df610ed5fcd/raw/spotify.md |
	sed -n 's/^.*(\([^ ]*\))$/\1/p';
);

# vim: set ft=sh :
