#!/usr/bin/env bash
#
# Export the dbus session address on startup so it can be used by cron.
# Based on: http://dev.gentoo.org/~tomka/mail.html
#
# other methode : source "${HOME}/.dbus/session-bus/$(dbus-uuidgen --get)"

spool_dir=${XDG_VAR_HOME}/spool;

> "${spool_dir}/xdbus";
chmod 600 "${spool_dir}/xdbus";

env \
| grep DBUS_SESSION_BUS_ADDRESS >> "${spool_dir}/xdbus";

printf '%s\n' "export DBUS_SESSION_BUS_ADDRESS" >> "${spool_dir}/xdbus";

# vim: set ft=sh :
